/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


static double *new_doublep() { 
  return (double *) calloc(1,sizeof(double)); 
}

static double *copy_doublep(double value) { 
  double *obj = (double *) calloc(1,sizeof(double));
  *obj = value;
  return obj; 
}

static void delete_doublep(double *obj) { 
  if (obj) free(obj); 
}

static void doublep_assign(double *obj, double value) {
  *obj = value;
}

static double doublep_value(double *obj) {
  return *obj;
}


static char *new_charp() { 
  return (char *) calloc(1,sizeof(char)); 
}

static char *copy_charp(char value) { 
  char *obj = (char *) calloc(1,sizeof(char));
  *obj = value;
  return obj; 
}

static void delete_charp(char *obj) { 
  if (obj) free(obj); 
}

static void charp_assign(char *obj, char value) {
  *obj = value;
}

static char charp_value(char *obj) {
  return *obj;
}


typedef double doubleArray;

SWIGINTERN doubleArray *new_doubleArray(int nelements){
  return (double *) calloc(nelements,sizeof(double));
}
SWIGINTERN void delete_doubleArray(doubleArray *self){
  free(self);
}
SWIGINTERN double doubleArray_getitem(doubleArray *self,int index){
  return self[index];
}
SWIGINTERN void doubleArray_setitem(doubleArray *self,int index,double value){
  self[index] = value;
}
SWIGINTERN double *doubleArray_cast(doubleArray *self){
  return self;
}
SWIGINTERN doubleArray *doubleArray_frompointer(double *t){
  return (doubleArray *) t;
}

#include "griddyn_export.h"
#include "griddyn_export_advanced.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_new_1doublep(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  double *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (double *)new_doublep();
  *(double **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_copy_1doublep(JNIEnv *jenv, jclass jcls, jdouble jarg1) {
  jlong jresult = 0 ;
  double arg1 ;
  double *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (double)jarg1; 
  result = (double *)copy_doublep(arg1);
  *(double **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_java_griddyn_griddynJNI_delete_1doublep(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  double *arg1 = (double *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(double **)&jarg1; 
  delete_doublep(arg1);
}


SWIGEXPORT void JNICALL Java_com_java_griddyn_griddynJNI_doublep_1assign(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2) {
  double *arg1 = (double *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(double **)&jarg1; 
  arg2 = (double)jarg2; 
  doublep_assign(arg1,arg2);
}


SWIGEXPORT jdouble JNICALL Java_com_java_griddyn_griddynJNI_doublep_1value(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jdouble jresult = 0 ;
  double *arg1 = (double *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(double **)&jarg1; 
  result = (double)doublep_value(arg1);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_java_griddyn_griddynJNI_new_1charp(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *)new_charp();
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_java_griddyn_griddynJNI_copy_1charp(JNIEnv *jenv, jclass jcls, jchar jarg1) {
  jstring jresult = 0 ;
  char arg1 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (char)jarg1; 
  result = (char *)copy_charp(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_java_griddyn_griddynJNI_delete_1charp(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  char *arg1 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  delete_charp(arg1);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT void JNICALL Java_com_java_griddyn_griddynJNI_charp_1assign(JNIEnv *jenv, jclass jcls, jstring jarg1, jchar jarg2) {
  char *arg1 = (char *) 0 ;
  char arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  arg2 = (char)jarg2; 
  charp_assign(arg1,arg2);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT jchar JNICALL Java_com_java_griddyn_griddynJNI_charp_1value(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jchar jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (char)charp_value(arg1);
  jresult = (jchar)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_new_1doubleArray(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  doubleArray *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (doubleArray *)new_doubleArray(arg1);
  *(doubleArray **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_java_griddyn_griddynJNI_delete_1doubleArray(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  doubleArray *arg1 = (doubleArray *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(doubleArray **)&jarg1; 
  delete_doubleArray(arg1);
}


SWIGEXPORT jdouble JNICALL Java_com_java_griddyn_griddynJNI_doubleArray_1getitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jdouble jresult = 0 ;
  doubleArray *arg1 = (doubleArray *) 0 ;
  int arg2 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(doubleArray **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (double)doubleArray_getitem(arg1,arg2);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_java_griddyn_griddynJNI_doubleArray_1setitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jdouble jarg3) {
  doubleArray *arg1 = (doubleArray *) 0 ;
  int arg2 ;
  double arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(doubleArray **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (double)jarg3; 
  doubleArray_setitem(arg1,arg2,arg3);
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_doubleArray_1cast(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  doubleArray *arg1 = (doubleArray *) 0 ;
  double *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(doubleArray **)&jarg1; 
  result = (double *)doubleArray_cast(arg1);
  *(double **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_doubleArray_1frompointer(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  double *arg1 = (double *) 0 ;
  doubleArray *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(double **)&jarg1; 
  result = (doubleArray *)doubleArray_frompointer(arg1);
  *(doubleArray **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1getResults_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3, jint jarg4) {
  jint jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  char *arg2 = (char *) 0 ;
  double *arg3 ;
  int arg4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(double **)&jarg3; 
  arg4 = (int)jarg4; 
  result = (int)gridDynSimulation_getResults(arg1,(char const *)arg2,arg3,arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_griddyn_1ok_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  griddyn_status_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (griddyn_status_enum)griddyn_ok;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_griddyn_1invalid_1object_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  griddyn_status_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (griddyn_status_enum)griddyn_invalid_object;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_griddyn_1invalid_1parameter_1value_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  griddyn_status_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (griddyn_status_enum)griddyn_invalid_parameter_value;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_griddyn_1unknown_1parameter_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  griddyn_status_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (griddyn_status_enum)griddyn_unknown_parameter;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_griddyn_1add_1failure_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  griddyn_status_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (griddyn_status_enum)griddyn_add_failure;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_griddyn_1remove_1failure_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  griddyn_status_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (griddyn_status_enum)griddyn_remove_failure;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_griddyn_1query_1load_1failure_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  griddyn_status_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (griddyn_status_enum)griddyn_query_load_failure;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_griddyn_1file_1load_1failure_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  griddyn_status_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (griddyn_status_enum)griddyn_file_load_failure;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_griddyn_1solve_1error_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  griddyn_status_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (griddyn_status_enum)griddyn_solve_error;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_griddyn_1object_1not_1initialized_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  griddyn_status_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (griddyn_status_enum)griddyn_object_not_initialized;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_griddyn_1invalid_1function_1call_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  griddyn_status_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (griddyn_status_enum)griddyn_invalid_function_call;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_griddyn_1function_1failure_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  griddyn_status_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (griddyn_status_enum)griddyn_function_failure;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_GRIDDYN_1PENDING_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)((25));
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_GRIDDYN_1COMPLETE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)((30));
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1create(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  gridDynObject result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (gridDynObject)gridDynObject_create((char const *)arg1,(char const *)arg2);
  *(gridDynObject *)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1clone(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) (gridDynObject)0 ;
  gridDynObject result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  result = (gridDynObject)gridDynObject_clone(arg1);
  *(gridDynObject *)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  gridDynObject arg1 = (gridDynObject) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  gridDynObject_free(arg1);
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1add(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) 0 ;
  gridDynObject arg2 = (gridDynObject) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  arg2 = *(gridDynObject *)&jarg2; 
  result = (griddyn_status)gridDynObject_add(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1remove(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) 0 ;
  gridDynObject arg2 = (gridDynObject) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  arg2 = *(gridDynObject *)&jarg2; 
  result = (griddyn_status)gridDynObject_remove(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1setString(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3) {
  jint jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (griddyn_status)gridDynObject_setString(arg1,(char const *)arg2,(char const *)arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1setValue(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jdouble jarg3) {
  jint jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) 0 ;
  char *arg2 = (char *) 0 ;
  double arg3 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (double)jarg3; 
  result = (griddyn_status)gridDynObject_setValue(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1setValueUnits(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jdouble jarg3, jstring jarg4) {
  jint jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) 0 ;
  char *arg2 = (char *) 0 ;
  double arg3 ;
  char *arg4 = (char *) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (double)jarg3; 
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
    if (!arg4) return 0;
  }
  result = (griddyn_status)gridDynObject_setValueUnits(arg1,(char const *)arg2,arg3,(char const *)arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg4) (*jenv)->ReleaseStringUTFChars(jenv, jarg4, (const char *)arg4);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1setFlag(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3) {
  jint jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (int)jarg3; 
  result = (griddyn_status)gridDynObject_setFlag(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1getString(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3, jint jarg4) {
  jint jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) (gridDynObject)0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int arg4 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = (int)jarg4; 
  result = (griddyn_status)gridDynObject_getString(arg1,(char const *)arg2,arg3,arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1getValue(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3) {
  jint jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) (gridDynObject)0 ;
  char *arg2 = (char *) 0 ;
  double *arg3 = (double *) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(double **)&jarg3; 
  result = (griddyn_status)gridDynObject_getValue(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1getValueUnits(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3, jlong jarg4) {
  jint jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) (gridDynObject)0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  double *arg4 = (double *) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = *(double **)&jarg4; 
  result = (griddyn_status)gridDynObject_getValueUnits(arg1,(char const *)arg2,(char const *)arg3,arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1getFlag(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3) {
  jint jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) (gridDynObject)0 ;
  char *arg2 = (char *) 0 ;
  int *arg3 = (int *) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(int **)&jarg3; 
  result = (griddyn_status)gridDynObject_getFlag(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1find(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) (gridDynObject)0 ;
  char *arg2 = (char *) 0 ;
  gridDynObject result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (gridDynObject)gridDynObject_find(arg1,(char const *)arg2);
  *(gridDynObject *)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1getSubObject(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3) {
  jlong jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) (gridDynObject)0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  gridDynObject result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (int)jarg3; 
  result = (gridDynObject)gridDynObject_getSubObject(arg1,(char const *)arg2,arg3);
  *(gridDynObject *)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1findByUserId(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3) {
  jlong jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) (gridDynObject)0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  gridDynObject result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (int)jarg3; 
  result = (gridDynObject)gridDynObject_findByUserId(arg1,(char const *)arg2,arg3);
  *(gridDynObject *)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1getParent(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) (gridDynObject)0 ;
  gridDynObject result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  result = (gridDynObject)gridDynObject_getParent(arg1);
  *(gridDynObject *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1getType(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) (gridDynObject)0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  result = (char *)gridDynObject_getType(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1create(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  gridDynSimReference result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (gridDynSimReference)gridDynSimulation_create((char const *)arg1,(char const *)arg2);
  *(gridDynSimReference *)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  gridDynSimulation_free(arg1);
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1initializeFromString(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jint jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  char *arg2 = (char *) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (griddyn_status)gridDynSimulation_initializeFromString(arg1,(char const *)arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1initializeFromArgs(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jint jarg4) {
  jint jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  int arg2 ;
  char **arg3 ;
  int arg4 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(char ***)&jarg3; 
  arg4 = (int)jarg4; 
  result = (griddyn_status)gridDynSimulation_initializeFromArgs(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1loadfile(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3) {
  jint jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (griddyn_status)gridDynSimulation_loadfile(arg1,(char const *)arg2,(char const *)arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1addCommand(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jint jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  char *arg2 = (char *) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (griddyn_status)gridDynSimulation_addCommand(arg1,(char const *)arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1powerflowInitialize(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  result = (griddyn_status)gridDynSimulation_powerflowInitialize(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1powerflow(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  result = (griddyn_status)gridDynSimulation_powerflow(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1dynamicInitialize(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  result = (griddyn_status)gridDynSimulation_dynamicInitialize(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1reset(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  result = (griddyn_status)gridDynSimulation_reset(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1getCurrentTime(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jdouble jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  result = (double)gridDynSimulation_getCurrentTime(arg1);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1run(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  result = (griddyn_status)gridDynSimulation_run(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1runTo(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2) {
  jint jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  double arg2 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  arg2 = (double)jarg2; 
  result = (griddyn_status)gridDynSimulation_runTo(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1Step(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  result = (griddyn_status)gridDynSimulation_Step(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1runAsync(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  result = (griddyn_status)gridDynSimulation_runAsync(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1runToAsync(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2) {
  jint jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  double arg2 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  arg2 = (double)jarg2; 
  result = (griddyn_status)gridDynSimulation_runToAsync(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1StepAsync(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  result = (griddyn_status)gridDynSimulation_StepAsync(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1getStatus(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  result = (int)gridDynSimulation_getStatus(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_getSimulationObject(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  gridDynObject result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  result = (gridDynObject)getSimulationObject(arg1);
  *(gridDynObject *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1getSolverKey(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  char *arg2 = (char *) 0 ;
  solverKey result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (solverKey)gridDynSimulation_getSolverKey(arg1,(char const *)arg2);
  *(solverKey *)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_java_griddyn_griddynJNI_gridDynSolverKey_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  solverKey arg1 = (solverKey) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(solverKey *)&jarg1; 
  gridDynSolverKey_free(arg1);
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1stateSize(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  solverKey arg2 = (solverKey) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  arg2 = *(solverKey *)&jarg2; 
  result = (int)gridDynSimulation_stateSize(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1busCount(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  result = (int)gridDynSimulation_busCount(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1lineCount(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  result = (int)gridDynSimulation_lineCount(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1guessState(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  double arg2 ;
  double *arg3 = (double *) 0 ;
  double *arg4 = (double *) 0 ;
  solverKey arg5 = (solverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  arg2 = (double)jarg2; 
  arg3 = *(double **)&jarg3; 
  arg4 = *(double **)&jarg4; 
  arg5 = *(solverKey *)&jarg5; 
  result = (griddyn_status)gridDynSimulation_guessState(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1setState(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  double arg2 ;
  double *arg3 = (double *) 0 ;
  double *arg4 = (double *) 0 ;
  solverKey arg5 = (solverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  arg2 = (double)jarg2; 
  arg3 = *(double **)&jarg3; 
  arg4 = *(double **)&jarg4; 
  arg5 = *(solverKey *)&jarg5; 
  result = (griddyn_status)gridDynSimulation_setState(arg1,arg2,(double const *)arg3,(double const *)arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1getStateVariableTypes(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  double *arg2 = (double *) 0 ;
  solverKey arg3 = (solverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  arg2 = *(double **)&jarg2; 
  arg3 = *(solverKey *)&jarg3; 
  result = (griddyn_status)gridDynSimulation_getStateVariableTypes(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1residual(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jlong jarg6) {
  jint jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  double arg2 ;
  double *arg3 = (double *) 0 ;
  double *arg4 = (double *) 0 ;
  double *arg5 = (double *) 0 ;
  solverKey arg6 = (solverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  arg2 = (double)jarg2; 
  arg3 = *(double **)&jarg3; 
  arg4 = *(double **)&jarg4; 
  arg5 = *(double **)&jarg5; 
  arg6 = *(solverKey *)&jarg6; 
  result = (griddyn_status)gridDynSimulation_residual(arg1,arg2,arg3,(double const *)arg4,(double const *)arg5,arg6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1derivative(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  double arg2 ;
  double *arg3 = (double *) 0 ;
  double *arg4 = (double *) 0 ;
  solverKey arg5 = (solverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  arg2 = (double)jarg2; 
  arg3 = *(double **)&jarg3; 
  arg4 = *(double **)&jarg4; 
  arg5 = *(solverKey *)&jarg5; 
  result = (griddyn_status)gridDynSimulation_derivative(arg1,arg2,arg3,(double const *)arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1algebraicUpdate(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2, jlong jarg3, jlong jarg4, jdouble jarg5, jlong jarg6) {
  jint jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  double arg2 ;
  double *arg3 = (double *) 0 ;
  double *arg4 = (double *) 0 ;
  double arg5 ;
  solverKey arg6 = (solverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  arg2 = (double)jarg2; 
  arg3 = *(double **)&jarg3; 
  arg4 = *(double **)&jarg4; 
  arg5 = (double)jarg5; 
  arg6 = *(solverKey *)&jarg6; 
  result = (griddyn_status)gridDynSimulation_algebraicUpdate(arg1,arg2,arg3,(double const *)arg4,arg5,arg6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulation_1jacobian(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2, jlong jarg3, jlong jarg4, jdouble jarg5, jlong jarg6, jlong jarg7) {
  jint jresult = 0 ;
  gridDynSimReference arg1 = (gridDynSimReference) 0 ;
  double arg2 ;
  double *arg3 = (double *) 0 ;
  double *arg4 = (double *) 0 ;
  double arg5 ;
  solverKey arg6 = (solverKey) 0 ;
  void (*arg7)(int,int,double) = (void (*)(int,int,double)) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSimReference *)&jarg1; 
  arg2 = (double)jarg2; 
  arg3 = *(double **)&jarg3; 
  arg4 = *(double **)&jarg4; 
  arg5 = (double)jarg5; 
  arg6 = *(solverKey *)&jarg6; 
  arg7 = *(void (**)(int,int,double))&jarg7; 
  result = (griddyn_status)gridDynSimulation_jacobian(arg1,arg2,(double const *)arg3,(double const *)arg4,arg5,arg6,arg7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_gridDynSingleQuery_1create(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) 0 ;
  char *arg2 = (char *) 0 ;
  gridDynSingleQuery result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (gridDynSingleQuery)gridDynSingleQuery_create(arg1,(char const *)arg2);
  *(gridDynSingleQuery *)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_gridDynVectorQuery_1create(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) 0 ;
  char *arg2 = (char *) 0 ;
  gridDynVectorQuery result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (gridDynVectorQuery)gridDynVectorQuery_create(arg1,(char const *)arg2);
  *(gridDynVectorQuery *)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_java_griddyn_griddynJNI_gridDynSingleQuery_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  gridDynSingleQuery arg1 = (gridDynSingleQuery) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSingleQuery *)&jarg1; 
  gridDynSingleQuery_free(arg1);
}


SWIGEXPORT void JNICALL Java_com_java_griddyn_griddynJNI_gridDynVectorQuery_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  gridDynVectorQuery arg1 = (gridDynVectorQuery) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynVectorQuery *)&jarg1; 
  gridDynVectorQuery_free(arg1);
}


SWIGEXPORT jdouble JNICALL Java_com_java_griddyn_griddynJNI_gridDynSingleQuery_1run(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jdouble jresult = 0 ;
  gridDynSingleQuery arg1 = (gridDynSingleQuery) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSingleQuery *)&jarg1; 
  result = (double)gridDynSingleQuery_run(arg1);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynVectorQuery_1run(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3) {
  jint jresult = 0 ;
  gridDynVectorQuery arg1 = (gridDynVectorQuery) 0 ;
  double *arg2 = (double *) 0 ;
  int arg3 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynVectorQuery *)&jarg1; 
  arg2 = *(double **)&jarg2; 
  arg3 = (int)jarg3; 
  result = (griddyn_status)gridDynVectorQuery_run(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynVectorQuery_1append(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jstring jarg3) {
  jint jresult = 0 ;
  gridDynVectorQuery arg1 = (gridDynVectorQuery) 0 ;
  gridDynObject arg2 = (gridDynObject) 0 ;
  char *arg3 = (char *) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynVectorQuery *)&jarg1; 
  arg2 = *(gridDynObject *)&jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (griddyn_status)gridDynVectorQuery_append(arg1,arg2,(char const *)arg3);
  jresult = (jint)result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSingleQuery_1update(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jstring jarg3) {
  jint jresult = 0 ;
  gridDynSingleQuery arg1 = (gridDynSingleQuery) 0 ;
  gridDynObject arg2 = (gridDynObject) 0 ;
  char *arg3 = (char *) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynSingleQuery *)&jarg1; 
  arg2 = *(gridDynObject *)&jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (griddyn_status)gridDynSingleQuery_update(arg1,arg2,(char const *)arg3);
  jresult = (jint)result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynVectorQuery_1update(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jstring jarg3) {
  jint jresult = 0 ;
  gridDynVectorQuery arg1 = (gridDynVectorQuery) 0 ;
  gridDynObject arg2 = (gridDynObject) 0 ;
  char *arg3 = (char *) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynVectorQuery *)&jarg1; 
  arg2 = *(gridDynObject *)&jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (griddyn_status)gridDynVectorQuery_update(arg1,arg2,(char const *)arg3);
  jresult = (jint)result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_gridDynEvent_1create(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  gridDynObject arg2 = (gridDynObject) 0 ;
  gridDynEvent result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = *(gridDynObject *)&jarg2; 
  result = (gridDynEvent)gridDynEvent_create((char const *)arg1,arg2);
  *(gridDynEvent *)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_java_griddyn_griddynJNI_gridDynEvent_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  gridDynEvent arg1 = (gridDynEvent) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynEvent *)&jarg1; 
  gridDynEvent_free(arg1);
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynEvent_1trigger(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  gridDynEvent arg1 = (gridDynEvent) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynEvent *)&jarg1; 
  result = (griddyn_status)gridDynEvent_trigger(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynEvent_1schedule(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  gridDynEvent arg1 = (gridDynEvent) 0 ;
  gridDynSimReference arg2 = (gridDynSimReference) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynEvent *)&jarg1; 
  arg2 = *(gridDynSimReference *)&jarg2; 
  result = (griddyn_status)gridDynEvent_schedule(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynEvent_1setValue(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jdouble jarg3) {
  jint jresult = 0 ;
  gridDynEvent arg1 = (gridDynEvent) 0 ;
  char *arg2 = (char *) 0 ;
  double arg3 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynEvent *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (double)jarg3; 
  result = (griddyn_status)gridDynEvent_setValue(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynEvent_1setString(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3) {
  jint jresult = 0 ;
  gridDynEvent arg1 = (gridDynEvent) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynEvent *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (griddyn_status)gridDynEvent_setString(arg1,(char const *)arg2,(char const *)arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynEvent_1setFlag(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3) {
  jint jresult = 0 ;
  gridDynEvent arg1 = (gridDynEvent) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynEvent *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (int)jarg3; 
  result = (griddyn_status)gridDynEvent_setFlag(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynEvent_1setTarget(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  gridDynEvent arg1 = (gridDynEvent) 0 ;
  gridDynObject arg2 = (gridDynObject) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynEvent *)&jarg1; 
  arg2 = *(gridDynObject *)&jarg2; 
  result = (griddyn_status)gridDynEvent_setTarget(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1stateSize(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) 0 ;
  solverKey arg2 = (solverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  arg2 = *(solverKey *)&jarg2; 
  result = (griddyn_status)gridDynObject_stateSize(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1guessState(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) 0 ;
  double arg2 ;
  double *arg3 = (double *) 0 ;
  double *arg4 = (double *) 0 ;
  solverKey arg5 = (solverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  arg2 = (double)jarg2; 
  arg3 = *(double **)&jarg3; 
  arg4 = *(double **)&jarg4; 
  arg5 = *(solverKey *)&jarg5; 
  result = (griddyn_status)gridDynObject_guessState(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1setState(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) 0 ;
  double arg2 ;
  double *arg3 = (double *) 0 ;
  double *arg4 = (double *) 0 ;
  solverKey arg5 = (solverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  arg2 = (double)jarg2; 
  arg3 = *(double **)&jarg3; 
  arg4 = *(double **)&jarg4; 
  arg5 = *(solverKey *)&jarg5; 
  result = (griddyn_status)gridDynObject_setState(arg1,arg2,(double const *)arg3,(double const *)arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1getStateVariableTypes(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) 0 ;
  double *arg2 = (double *) 0 ;
  solverKey arg3 = (solverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  arg2 = *(double **)&jarg2; 
  arg3 = *(solverKey *)&jarg3; 
  result = (griddyn_status)gridDynObject_getStateVariableTypes(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1residual(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) 0 ;
  double *arg2 = (double *) 0 ;
  int arg3 ;
  double *arg4 = (double *) 0 ;
  solverKey arg5 = (solverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  arg2 = *(double **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(double **)&jarg4; 
  arg5 = *(solverKey *)&jarg5; 
  result = (griddyn_status)gridDynObject_residual(arg1,(double const *)arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1derivative(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) 0 ;
  double *arg2 = (double *) 0 ;
  int arg3 ;
  double *arg4 = (double *) 0 ;
  solverKey arg5 = (solverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  arg2 = *(double **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(double **)&jarg4; 
  arg5 = *(solverKey *)&jarg5; 
  result = (griddyn_status)gridDynObject_derivative(arg1,(double const *)arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1algebraicUpdate(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jlong jarg4, jdouble jarg5, jlong jarg6) {
  jint jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) 0 ;
  double *arg2 = (double *) 0 ;
  int arg3 ;
  double *arg4 = (double *) 0 ;
  double arg5 ;
  solverKey arg6 = (solverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  arg2 = *(double **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(double **)&jarg4; 
  arg5 = (double)jarg5; 
  arg6 = *(solverKey *)&jarg6; 
  result = (griddyn_status)gridDynObject_algebraicUpdate(arg1,(double const *)arg2,arg3,arg4,arg5,arg6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1jacobian(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jdouble jarg4, jlong jarg5, jlong jarg6) {
  jint jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) 0 ;
  double *arg2 = (double *) 0 ;
  int arg3 ;
  double arg4 ;
  void (*arg5)(int,int,double) = (void (*)(int,int,double)) 0 ;
  solverKey arg6 = (solverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  arg2 = *(double **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (double)jarg4; 
  arg5 = *(void (**)(int,int,double))&jarg5; 
  arg6 = *(solverKey *)&jarg6; 
  result = (griddyn_status)gridDynObject_jacobian(arg1,(double const *)arg2,arg3,arg4,arg5,arg6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1ioPartialDerivatives(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) 0 ;
  double *arg2 = (double *) 0 ;
  int arg3 ;
  void (*arg4)(int,int,double) = (void (*)(int,int,double)) 0 ;
  solverKey arg5 = (solverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  arg2 = *(double **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(void (**)(int,int,double))&jarg4; 
  arg5 = *(solverKey *)&jarg5; 
  result = (griddyn_status)gridDynObject_ioPartialDerivatives(arg1,(double const *)arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObject_1outputPartialDerivatives(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  gridDynObject arg1 = (gridDynObject) 0 ;
  double *arg2 = (double *) 0 ;
  int arg3 ;
  void (*arg4)(int,int,double) = (void (*)(int,int,double)) 0 ;
  solverKey arg5 = (solverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(gridDynObject *)&jarg1; 
  arg2 = *(double **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(void (**)(int,int,double))&jarg4; 
  arg5 = *(solverKey *)&jarg5; 
  result = (griddyn_status)gridDynObject_outputPartialDerivatives(arg1,(double const *)arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

