/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.java.griddyn;

public interface griddynConstants {
  public final static int GRIDDYN_PENDING = griddynJNI.GRIDDYN_PENDING_get();
  public final static int GRIDDYN_COMPLETE = griddynJNI.GRIDDYN_COMPLETE_get();
}
