/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.java.griddyn;

public class griddyn implements griddynConstants {
  public static SWIGTYPE_p_double new_doublep() {
    long cPtr = griddynJNI.new_doublep();
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static SWIGTYPE_p_double copy_doublep(double value) {
    long cPtr = griddynJNI.copy_doublep(value);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static void delete_doublep(SWIGTYPE_p_double obj) {
    griddynJNI.delete_doublep(SWIGTYPE_p_double.getCPtr(obj));
  }

  public static void doublep_assign(SWIGTYPE_p_double obj, double value) {
    griddynJNI.doublep_assign(SWIGTYPE_p_double.getCPtr(obj), value);
  }

  public static double doublep_value(SWIGTYPE_p_double obj) {
    return griddynJNI.doublep_value(SWIGTYPE_p_double.getCPtr(obj));
  }

  public static String new_charp() {
    return griddynJNI.new_charp();
  }

  public static String copy_charp(char value) {
    return griddynJNI.copy_charp(value);
  }

  public static void delete_charp(String obj) {
    griddynJNI.delete_charp(obj);
  }

  public static void charp_assign(String obj, char value) {
    griddynJNI.charp_assign(obj, value);
  }

  public static char charp_value(String obj) {
    return griddynJNI.charp_value(obj);
  }

  public static int gridDynSimulationGetResults(SWIGTYPE_p_void sim, String datatype, SWIGTYPE_p_double data, int maxSize) {
    return griddynJNI.gridDynSimulationGetResults__SWIG_0(SWIGTYPE_p_void.getCPtr(sim), datatype, SWIGTYPE_p_double.getCPtr(data), maxSize);
  }

  public static SWIGTYPE_p_void gridDynObjectCreate(String componentType, String objectType) {
    long cPtr = griddynJNI.gridDynObjectCreate(componentType, objectType);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static SWIGTYPE_p_void gridDynObjectClone(SWIGTYPE_p_void obj) {
    long cPtr = griddynJNI.gridDynObjectClone(SWIGTYPE_p_void.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static void gridDynObjectFree(SWIGTYPE_p_void obj) {
    griddynJNI.gridDynObjectFree(SWIGTYPE_p_void.getCPtr(obj));
  }

  public static int gridDynObjectAdd(SWIGTYPE_p_void parentObject, SWIGTYPE_p_void objectToAdd) {
    return griddynJNI.gridDynObjectAdd(SWIGTYPE_p_void.getCPtr(parentObject), SWIGTYPE_p_void.getCPtr(objectToAdd));
  }

  public static int gridDynObjectRemove(SWIGTYPE_p_void parentObject, SWIGTYPE_p_void objectToRemove) {
    return griddynJNI.gridDynObjectRemove(SWIGTYPE_p_void.getCPtr(parentObject), SWIGTYPE_p_void.getCPtr(objectToRemove));
  }

  public static int gridDynObjectSetString(SWIGTYPE_p_void obj, String parameter, String value) {
    return griddynJNI.gridDynObjectSetString(SWIGTYPE_p_void.getCPtr(obj), parameter, value);
  }

  public static int gridDynObjectSetValue(SWIGTYPE_p_void obj, String parameter, double value) {
    return griddynJNI.gridDynObjectSetValue(SWIGTYPE_p_void.getCPtr(obj), parameter, value);
  }

  public static int gridDynObjectSetValueUnits(SWIGTYPE_p_void obj, String parameter, double value, String units) {
    return griddynJNI.gridDynObjectSetValueUnits(SWIGTYPE_p_void.getCPtr(obj), parameter, value, units);
  }

  public static int gridDynObjectSetFlag(SWIGTYPE_p_void obj, String flag, int val) {
    return griddynJNI.gridDynObjectSetFlag(SWIGTYPE_p_void.getCPtr(obj), flag, val);
  }

  public static int gridDynObjectGetString(SWIGTYPE_p_void obj, String parameter, String value, int N) {
    return griddynJNI.gridDynObjectGetString(SWIGTYPE_p_void.getCPtr(obj), parameter, value, N);
  }

  public static int gridDynObjectGetValue(SWIGTYPE_p_void obj, String parameter, SWIGTYPE_p_double result) {
    return griddynJNI.gridDynObjectGetValue(SWIGTYPE_p_void.getCPtr(obj), parameter, SWIGTYPE_p_double.getCPtr(result));
  }

  public static int gridDynObjectGetValueUnits(SWIGTYPE_p_void obj, String parameter, String units, SWIGTYPE_p_double result) {
    return griddynJNI.gridDynObjectGetValueUnits(SWIGTYPE_p_void.getCPtr(obj), parameter, units, SWIGTYPE_p_double.getCPtr(result));
  }

  public static int gridDynObjectGetFlag(SWIGTYPE_p_void obj, String flag, SWIGTYPE_p_int result) {
    return griddynJNI.gridDynObjectGetFlag(SWIGTYPE_p_void.getCPtr(obj), flag, SWIGTYPE_p_int.getCPtr(result));
  }

  public static SWIGTYPE_p_void gridDynObjectFind(SWIGTYPE_p_void obj, String objectToFind) {
    long cPtr = griddynJNI.gridDynObjectFind(SWIGTYPE_p_void.getCPtr(obj), objectToFind);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static SWIGTYPE_p_void gridDynObjectGetSubObject(SWIGTYPE_p_void obj, String componentType, int N) {
    long cPtr = griddynJNI.gridDynObjectGetSubObject(SWIGTYPE_p_void.getCPtr(obj), componentType, N);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static SWIGTYPE_p_void gridDynObjectFindByUserId(SWIGTYPE_p_void obj, String componentType, int ID) {
    long cPtr = griddynJNI.gridDynObjectFindByUserId(SWIGTYPE_p_void.getCPtr(obj), componentType, ID);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static SWIGTYPE_p_void gridDynObjectGetParent(SWIGTYPE_p_void obj) {
    long cPtr = griddynJNI.gridDynObjectGetParent(SWIGTYPE_p_void.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static String gridDynObjectGetType(SWIGTYPE_p_void obj) {
    return griddynJNI.gridDynObjectGetType(SWIGTYPE_p_void.getCPtr(obj));
  }

  public static SWIGTYPE_p_void gridDynSimulationCreate(String type, String name) {
    long cPtr = griddynJNI.gridDynSimulationCreate(type, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static void gridDynSimulationFree(SWIGTYPE_p_void sim) {
    griddynJNI.gridDynSimulationFree(SWIGTYPE_p_void.getCPtr(sim));
  }

  public static int gridDynSimulationInitializeFromString(SWIGTYPE_p_void sim, String initializationString) {
    return griddynJNI.gridDynSimulationInitializeFromString(SWIGTYPE_p_void.getCPtr(sim), initializationString);
  }

  public static int gridDynSimulationInitializeFromArgs(SWIGTYPE_p_void sim, int argc, SWIGTYPE_p_p_char argv, int ignoreUnrecognized) {
    return griddynJNI.gridDynSimulationInitializeFromArgs(SWIGTYPE_p_void.getCPtr(sim), argc, SWIGTYPE_p_p_char.getCPtr(argv), ignoreUnrecognized);
  }

  public static int gridDynSimulationLoadfile(SWIGTYPE_p_void sim, String fileName, String fileType) {
    return griddynJNI.gridDynSimulationLoadfile(SWIGTYPE_p_void.getCPtr(sim), fileName, fileType);
  }

  public static int gridDynSimulationAddCommand(SWIGTYPE_p_void sim, String command) {
    return griddynJNI.gridDynSimulationAddCommand(SWIGTYPE_p_void.getCPtr(sim), command);
  }

  public static int gridDynSimulationPowerflowInitialize(SWIGTYPE_p_void sim) {
    return griddynJNI.gridDynSimulationPowerflowInitialize(SWIGTYPE_p_void.getCPtr(sim));
  }

  public static int gridDynSimulationPowerflow(SWIGTYPE_p_void sim) {
    return griddynJNI.gridDynSimulationPowerflow(SWIGTYPE_p_void.getCPtr(sim));
  }

  public static int gridDynSimulationDynamicInitialize(SWIGTYPE_p_void sim) {
    return griddynJNI.gridDynSimulationDynamicInitialize(SWIGTYPE_p_void.getCPtr(sim));
  }

  public static int gridDynSimulationReset(SWIGTYPE_p_void sim) {
    return griddynJNI.gridDynSimulationReset(SWIGTYPE_p_void.getCPtr(sim));
  }

  public static double gridDynSimulationGetCurrentTime(SWIGTYPE_p_void sim) {
    return griddynJNI.gridDynSimulationGetCurrentTime(SWIGTYPE_p_void.getCPtr(sim));
  }

  public static int gridDynSimulationRun(SWIGTYPE_p_void sim) {
    return griddynJNI.gridDynSimulationRun(SWIGTYPE_p_void.getCPtr(sim));
  }

  public static int gridDynSimulationRunTo(SWIGTYPE_p_void sim, double runToTime) {
    return griddynJNI.gridDynSimulationRunTo(SWIGTYPE_p_void.getCPtr(sim), runToTime);
  }

  public static int gridDynSimulationStep(SWIGTYPE_p_void sim) {
    return griddynJNI.gridDynSimulationStep(SWIGTYPE_p_void.getCPtr(sim));
  }

  public static int gridDynSimulationRunAsync(SWIGTYPE_p_void sim) {
    return griddynJNI.gridDynSimulationRunAsync(SWIGTYPE_p_void.getCPtr(sim));
  }

  public static int gridDynSimulationRunToAsync(SWIGTYPE_p_void sim, double runToTime) {
    return griddynJNI.gridDynSimulationRunToAsync(SWIGTYPE_p_void.getCPtr(sim), runToTime);
  }

  public static int gridDynSimulationStepAsync(SWIGTYPE_p_void sim) {
    return griddynJNI.gridDynSimulationStepAsync(SWIGTYPE_p_void.getCPtr(sim));
  }

  public static int gridDynSimulationGetStatus(SWIGTYPE_p_void sim) {
    return griddynJNI.gridDynSimulationGetStatus(SWIGTYPE_p_void.getCPtr(sim));
  }

  public static SWIGTYPE_p_void getSimulationObject(SWIGTYPE_p_void sim) {
    long cPtr = griddynJNI.getSimulationObject(SWIGTYPE_p_void.getCPtr(sim));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static SWIGTYPE_p_void gridDynSimulationGetSolverKey(SWIGTYPE_p_void sim, String solverType) {
    long cPtr = griddynJNI.gridDynSimulationGetSolverKey(SWIGTYPE_p_void.getCPtr(sim), solverType);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static void gridDynSolverKeyFree(SWIGTYPE_p_void key) {
    griddynJNI.gridDynSolverKeyFree(SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynSimulationStateSize(SWIGTYPE_p_void sim, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynSimulationStateSize(SWIGTYPE_p_void.getCPtr(sim), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynSimulationBusCount(SWIGTYPE_p_void sim) {
    return griddynJNI.gridDynSimulationBusCount(SWIGTYPE_p_void.getCPtr(sim));
  }

  public static int gridDynSimulationLineCount(SWIGTYPE_p_void sim) {
    return griddynJNI.gridDynSimulationLineCount(SWIGTYPE_p_void.getCPtr(sim));
  }

  public static int gridDynSimulationGuessState(SWIGTYPE_p_void sim, double time, SWIGTYPE_p_double states, SWIGTYPE_p_double dstate_dt, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynSimulationGuessState(SWIGTYPE_p_void.getCPtr(sim), time, SWIGTYPE_p_double.getCPtr(states), SWIGTYPE_p_double.getCPtr(dstate_dt), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynSimulationSetState(SWIGTYPE_p_void sim, double time, SWIGTYPE_p_double states, SWIGTYPE_p_double dstate_dt, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynSimulationSetState(SWIGTYPE_p_void.getCPtr(sim), time, SWIGTYPE_p_double.getCPtr(states), SWIGTYPE_p_double.getCPtr(dstate_dt), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynSimulationGetStateVariableTypes(SWIGTYPE_p_void sim, SWIGTYPE_p_double types, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynSimulationGetStateVariableTypes(SWIGTYPE_p_void.getCPtr(sim), SWIGTYPE_p_double.getCPtr(types), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynSimulationResidual(SWIGTYPE_p_void sim, double time, SWIGTYPE_p_double resid, SWIGTYPE_p_double states, SWIGTYPE_p_double dstate_dt, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynSimulationResidual(SWIGTYPE_p_void.getCPtr(sim), time, SWIGTYPE_p_double.getCPtr(resid), SWIGTYPE_p_double.getCPtr(states), SWIGTYPE_p_double.getCPtr(dstate_dt), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynSimulationDerivative(SWIGTYPE_p_void sim, double time, SWIGTYPE_p_double deriv, SWIGTYPE_p_double states, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynSimulationDerivative(SWIGTYPE_p_void.getCPtr(sim), time, SWIGTYPE_p_double.getCPtr(deriv), SWIGTYPE_p_double.getCPtr(states), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynSimulationAlgebraicUpdate(SWIGTYPE_p_void sim, double time, SWIGTYPE_p_double update, SWIGTYPE_p_double states, double alpha, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynSimulationAlgebraicUpdate(SWIGTYPE_p_void.getCPtr(sim), time, SWIGTYPE_p_double.getCPtr(update), SWIGTYPE_p_double.getCPtr(states), alpha, SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynSimulationJacobian(SWIGTYPE_p_void sim, double time, SWIGTYPE_p_double states, SWIGTYPE_p_double dstate_dt, double cj, SWIGTYPE_p_void key, SWIGTYPE_p_f_int_int_double__void insert) {
    return griddynJNI.gridDynSimulationJacobian(SWIGTYPE_p_void.getCPtr(sim), time, SWIGTYPE_p_double.getCPtr(states), SWIGTYPE_p_double.getCPtr(dstate_dt), cj, SWIGTYPE_p_void.getCPtr(key), SWIGTYPE_p_f_int_int_double__void.getCPtr(insert));
  }

  public static SWIGTYPE_p_void gridDynSingleQueryCreate(SWIGTYPE_p_void obj, String queryString) {
    long cPtr = griddynJNI.gridDynSingleQueryCreate(SWIGTYPE_p_void.getCPtr(obj), queryString);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static SWIGTYPE_p_void gridDynVectorQueryCreate(SWIGTYPE_p_void obj, String queryString) {
    long cPtr = griddynJNI.gridDynVectorQueryCreate(SWIGTYPE_p_void.getCPtr(obj), queryString);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static void gridDynSingleQueryFree(SWIGTYPE_p_void query) {
    griddynJNI.gridDynSingleQueryFree(SWIGTYPE_p_void.getCPtr(query));
  }

  public static void gridDynVectorQueryFree(SWIGTYPE_p_void query) {
    griddynJNI.gridDynVectorQueryFree(SWIGTYPE_p_void.getCPtr(query));
  }

  public static double gridDynSingleQueryRun(SWIGTYPE_p_void query) {
    return griddynJNI.gridDynSingleQueryRun(SWIGTYPE_p_void.getCPtr(query));
  }

  public static int gridDynVectorQueryRun(SWIGTYPE_p_void query, SWIGTYPE_p_double data, int N) {
    return griddynJNI.gridDynVectorQueryRun(SWIGTYPE_p_void.getCPtr(query), SWIGTYPE_p_double.getCPtr(data), N);
  }

  public static int gridDynVectorQueryAppend(SWIGTYPE_p_void query, SWIGTYPE_p_void obj, String queryString) {
    return griddynJNI.gridDynVectorQueryAppend(SWIGTYPE_p_void.getCPtr(query), SWIGTYPE_p_void.getCPtr(obj), queryString);
  }

  public static int gridDynSingleQueryUpdate(SWIGTYPE_p_void query, SWIGTYPE_p_void obj, String queryString) {
    return griddynJNI.gridDynSingleQueryUpdate(SWIGTYPE_p_void.getCPtr(query), SWIGTYPE_p_void.getCPtr(obj), queryString);
  }

  public static int gridDynVectorQueryUpdate(SWIGTYPE_p_void query, SWIGTYPE_p_void obj, String queryString) {
    return griddynJNI.gridDynVectorQueryUpdate(SWIGTYPE_p_void.getCPtr(query), SWIGTYPE_p_void.getCPtr(obj), queryString);
  }

  public static SWIGTYPE_p_void gridDynEventCreate(String eventString, SWIGTYPE_p_void obj) {
    long cPtr = griddynJNI.gridDynEventCreate(eventString, SWIGTYPE_p_void.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static void gridDynEventFree(SWIGTYPE_p_void evnt) {
    griddynJNI.gridDynEventFree(SWIGTYPE_p_void.getCPtr(evnt));
  }

  public static int gridDynEventTrigger(SWIGTYPE_p_void evnt) {
    return griddynJNI.gridDynEventTrigger(SWIGTYPE_p_void.getCPtr(evnt));
  }

  public static int gridDynEventSchedule(SWIGTYPE_p_void evnt, SWIGTYPE_p_void sim) {
    return griddynJNI.gridDynEventSchedule(SWIGTYPE_p_void.getCPtr(evnt), SWIGTYPE_p_void.getCPtr(sim));
  }

  public static int gridDynEventSetValue(SWIGTYPE_p_void evnt, String parameter, double value) {
    return griddynJNI.gridDynEventSetValue(SWIGTYPE_p_void.getCPtr(evnt), parameter, value);
  }

  public static int gridDynEventSetString(SWIGTYPE_p_void evnt, String parameter, String value) {
    return griddynJNI.gridDynEventSetString(SWIGTYPE_p_void.getCPtr(evnt), parameter, value);
  }

  public static int gridDynEventSetFlag(SWIGTYPE_p_void evnt, String flag, int val) {
    return griddynJNI.gridDynEventSetFlag(SWIGTYPE_p_void.getCPtr(evnt), flag, val);
  }

  public static int gridDynEventSetTarget(SWIGTYPE_p_void evnt, SWIGTYPE_p_void obj) {
    return griddynJNI.gridDynEventSetTarget(SWIGTYPE_p_void.getCPtr(evnt), SWIGTYPE_p_void.getCPtr(obj));
  }

  public static int gridDynObjectStateSize(SWIGTYPE_p_void obj, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynObjectStateSize(SWIGTYPE_p_void.getCPtr(obj), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynObjectGuessState(SWIGTYPE_p_void obj, double time, SWIGTYPE_p_double states, SWIGTYPE_p_double dstate_dt, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynObjectGuessState(SWIGTYPE_p_void.getCPtr(obj), time, SWIGTYPE_p_double.getCPtr(states), SWIGTYPE_p_double.getCPtr(dstate_dt), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynObjectSetState(SWIGTYPE_p_void obj, double time, SWIGTYPE_p_double states, SWIGTYPE_p_double dstate_dt, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynObjectSetState(SWIGTYPE_p_void.getCPtr(obj), time, SWIGTYPE_p_double.getCPtr(states), SWIGTYPE_p_double.getCPtr(dstate_dt), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynObjectGetStateVariableTypes(SWIGTYPE_p_void obj, SWIGTYPE_p_double types, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynObjectGetStateVariableTypes(SWIGTYPE_p_void.getCPtr(obj), SWIGTYPE_p_double.getCPtr(types), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynObjectResidual(SWIGTYPE_p_void obj, SWIGTYPE_p_double inputs, int inputSize, SWIGTYPE_p_double resid, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynObjectResidual(SWIGTYPE_p_void.getCPtr(obj), SWIGTYPE_p_double.getCPtr(inputs), inputSize, SWIGTYPE_p_double.getCPtr(resid), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynObjectDerivative(SWIGTYPE_p_void obj, SWIGTYPE_p_double inputs, int inputSize, SWIGTYPE_p_double deriv, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynObjectDerivative(SWIGTYPE_p_void.getCPtr(obj), SWIGTYPE_p_double.getCPtr(inputs), inputSize, SWIGTYPE_p_double.getCPtr(deriv), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynObjectAlgebraicUpdate(SWIGTYPE_p_void obj, SWIGTYPE_p_double inputs, int inputSize, SWIGTYPE_p_double update, double alpha, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynObjectAlgebraicUpdate(SWIGTYPE_p_void.getCPtr(obj), SWIGTYPE_p_double.getCPtr(inputs), inputSize, SWIGTYPE_p_double.getCPtr(update), alpha, SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynObjectJacobian(SWIGTYPE_p_void obj, SWIGTYPE_p_double inputs, int inputSize, double cj, SWIGTYPE_p_f_int_int_double__void insert, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynObjectJacobian(SWIGTYPE_p_void.getCPtr(obj), SWIGTYPE_p_double.getCPtr(inputs), inputSize, cj, SWIGTYPE_p_f_int_int_double__void.getCPtr(insert), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynObjectIoPartialDerivatives(SWIGTYPE_p_void obj, SWIGTYPE_p_double inputs, int inputSize, SWIGTYPE_p_f_int_int_double__void insert, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynObjectIoPartialDerivatives(SWIGTYPE_p_void.getCPtr(obj), SWIGTYPE_p_double.getCPtr(inputs), inputSize, SWIGTYPE_p_f_int_int_double__void.getCPtr(insert), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynObjectOutputPartialDerivatives(SWIGTYPE_p_void obj, SWIGTYPE_p_double inputs, int inputSize, SWIGTYPE_p_f_int_int_double__void insert, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynObjectOutputPartialDerivatives(SWIGTYPE_p_void.getCPtr(obj), SWIGTYPE_p_double.getCPtr(inputs), inputSize, SWIGTYPE_p_f_int_int_double__void.getCPtr(insert), SWIGTYPE_p_void.getCPtr(key));
  }

}
