/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


static double *new_doublep() { 
  return (double *) calloc(1,sizeof(double)); 
}

static double *copy_doublep(double value) { 
  double *obj = (double *) calloc(1,sizeof(double));
  *obj = value;
  return obj; 
}

static void delete_doublep(double *obj) { 
  if (obj) free(obj); 
}

static void doublep_assign(double *obj, double value) {
  *obj = value;
}

static double doublep_value(double *obj) {
  return *obj;
}


static char *new_charp() { 
  return (char *) calloc(1,sizeof(char)); 
}

static char *copy_charp(char value) { 
  char *obj = (char *) calloc(1,sizeof(char));
  *obj = value;
  return obj; 
}

static void delete_charp(char *obj) { 
  if (obj) free(obj); 
}

static void charp_assign(char *obj, char value) {
  *obj = value;
}

static char charp_value(char *obj) {
  return *obj;
}


typedef double doubleArray;

SWIGINTERN doubleArray *new_doubleArray(int nelements){
  return (double *) calloc(nelements,sizeof(double));
}
SWIGINTERN void delete_doubleArray(doubleArray *self){
  free(self);
}
SWIGINTERN double doubleArray_getitem(doubleArray *self,int index){
  return self[index];
}
SWIGINTERN void doubleArray_setitem(doubleArray *self,int index,double value){
  self[index] = value;
}
SWIGINTERN double *doubleArray_cast(doubleArray *self){
  return self;
}
SWIGINTERN doubleArray *doubleArray_frompointer(double *t){
  return (doubleArray *) t;
}

#include "griddyn_export.h"
#include "griddyn_export_advanced.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_new_1doublep(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  double *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (double *)new_doublep();
  *(double **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_copy_1doublep(JNIEnv *jenv, jclass jcls, jdouble jarg1) {
  jlong jresult = 0 ;
  double arg1 ;
  double *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (double)jarg1; 
  result = (double *)copy_doublep(arg1);
  *(double **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_java_griddyn_griddynJNI_delete_1doublep(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  double *arg1 = (double *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(double **)&jarg1; 
  delete_doublep(arg1);
}


SWIGEXPORT void JNICALL Java_com_java_griddyn_griddynJNI_doublep_1assign(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2) {
  double *arg1 = (double *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(double **)&jarg1; 
  arg2 = (double)jarg2; 
  doublep_assign(arg1,arg2);
}


SWIGEXPORT jdouble JNICALL Java_com_java_griddyn_griddynJNI_doublep_1value(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jdouble jresult = 0 ;
  double *arg1 = (double *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(double **)&jarg1; 
  result = (double)doublep_value(arg1);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_java_griddyn_griddynJNI_new_1charp(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *)new_charp();
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_java_griddyn_griddynJNI_copy_1charp(JNIEnv *jenv, jclass jcls, jchar jarg1) {
  jstring jresult = 0 ;
  char arg1 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (char)jarg1; 
  result = (char *)copy_charp(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_java_griddyn_griddynJNI_delete_1charp(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  char *arg1 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  delete_charp(arg1);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT void JNICALL Java_com_java_griddyn_griddynJNI_charp_1assign(JNIEnv *jenv, jclass jcls, jstring jarg1, jchar jarg2) {
  char *arg1 = (char *) 0 ;
  char arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  arg2 = (char)jarg2; 
  charp_assign(arg1,arg2);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT jchar JNICALL Java_com_java_griddyn_griddynJNI_charp_1value(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jchar jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (char)charp_value(arg1);
  jresult = (jchar)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_new_1doubleArray(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  doubleArray *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (doubleArray *)new_doubleArray(arg1);
  *(doubleArray **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_java_griddyn_griddynJNI_delete_1doubleArray(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  doubleArray *arg1 = (doubleArray *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(doubleArray **)&jarg1; 
  delete_doubleArray(arg1);
}


SWIGEXPORT jdouble JNICALL Java_com_java_griddyn_griddynJNI_doubleArray_1getitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jdouble jresult = 0 ;
  doubleArray *arg1 = (doubleArray *) 0 ;
  int arg2 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(doubleArray **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (double)doubleArray_getitem(arg1,arg2);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_java_griddyn_griddynJNI_doubleArray_1setitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jdouble jarg3) {
  doubleArray *arg1 = (doubleArray *) 0 ;
  int arg2 ;
  double arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(doubleArray **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (double)jarg3; 
  doubleArray_setitem(arg1,arg2,arg3);
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_doubleArray_1cast(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  doubleArray *arg1 = (doubleArray *) 0 ;
  double *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(doubleArray **)&jarg1; 
  result = (double *)doubleArray_cast(arg1);
  *(double **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_doubleArray_1frompointer(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  double *arg1 = (double *) 0 ;
  doubleArray *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(double **)&jarg1; 
  result = (doubleArray *)doubleArray_frompointer(arg1);
  *(doubleArray **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationGetResults_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3, jint jarg4) {
  jint jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  char *arg2 = (char *) 0 ;
  double *arg3 ;
  int arg4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(double **)&jarg3; 
  arg4 = (int)jarg4; 
  result = (int)gridDynSimulationGetResults(arg1,(char const *)arg2,arg3,arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_griddyn_1ok_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  griddyn_status_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (griddyn_status_enum)griddyn_ok;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_griddyn_1invalid_1object_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  griddyn_status_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (griddyn_status_enum)griddyn_invalid_object;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_griddyn_1invalid_1parameter_1value_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  griddyn_status_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (griddyn_status_enum)griddyn_invalid_parameter_value;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_griddyn_1unknown_1parameter_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  griddyn_status_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (griddyn_status_enum)griddyn_unknown_parameter;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_griddyn_1add_1failure_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  griddyn_status_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (griddyn_status_enum)griddyn_add_failure;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_griddyn_1remove_1failure_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  griddyn_status_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (griddyn_status_enum)griddyn_remove_failure;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_griddyn_1query_1load_1failure_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  griddyn_status_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (griddyn_status_enum)griddyn_query_load_failure;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_griddyn_1file_1load_1failure_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  griddyn_status_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (griddyn_status_enum)griddyn_file_load_failure;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_griddyn_1solve_1error_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  griddyn_status_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (griddyn_status_enum)griddyn_solve_error;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_griddyn_1object_1not_1initialized_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  griddyn_status_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (griddyn_status_enum)griddyn_object_not_initialized;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_griddyn_1invalid_1function_1call_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  griddyn_status_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (griddyn_status_enum)griddyn_invalid_function_call;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_griddyn_1function_1failure_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  griddyn_status_enum result;
  
  (void)jenv;
  (void)jcls;
  result = (griddyn_status_enum)griddyn_function_failure;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_GRIDDYN_1PENDING_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)((25));
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_GRIDDYN_1COMPLETE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)((30));
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectCreate(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  GridDynObject result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (GridDynObject)gridDynObjectCreate((char const *)arg1,(char const *)arg2);
  *(GridDynObject *)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectClone(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) (GridDynObject)0 ;
  GridDynObject result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  result = (GridDynObject)gridDynObjectClone(arg1);
  *(GridDynObject *)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectFree(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  GridDynObject arg1 = (GridDynObject) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  gridDynObjectFree(arg1);
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectAdd(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) 0 ;
  GridDynObject arg2 = (GridDynObject) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  arg2 = *(GridDynObject *)&jarg2; 
  result = (griddyn_status)gridDynObjectAdd(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectRemove(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) 0 ;
  GridDynObject arg2 = (GridDynObject) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  arg2 = *(GridDynObject *)&jarg2; 
  result = (griddyn_status)gridDynObjectRemove(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectSetString(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3) {
  jint jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (griddyn_status)gridDynObjectSetString(arg1,(char const *)arg2,(char const *)arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectSetValue(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jdouble jarg3) {
  jint jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) 0 ;
  char *arg2 = (char *) 0 ;
  double arg3 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (double)jarg3; 
  result = (griddyn_status)gridDynObjectSetValue(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectSetValueUnits(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jdouble jarg3, jstring jarg4) {
  jint jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) 0 ;
  char *arg2 = (char *) 0 ;
  double arg3 ;
  char *arg4 = (char *) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (double)jarg3; 
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
    if (!arg4) return 0;
  }
  result = (griddyn_status)gridDynObjectSetValueUnits(arg1,(char const *)arg2,arg3,(char const *)arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg4) (*jenv)->ReleaseStringUTFChars(jenv, jarg4, (const char *)arg4);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectSetFlag(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3) {
  jint jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (int)jarg3; 
  result = (griddyn_status)gridDynObjectSetFlag(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectGetString(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3, jint jarg4) {
  jint jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) (GridDynObject)0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int arg4 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = (int)jarg4; 
  result = (griddyn_status)gridDynObjectGetString(arg1,(char const *)arg2,arg3,arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectGetValue(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3) {
  jint jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) (GridDynObject)0 ;
  char *arg2 = (char *) 0 ;
  double *arg3 = (double *) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(double **)&jarg3; 
  result = (griddyn_status)gridDynObjectGetValue(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectGetValueUnits(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3, jlong jarg4) {
  jint jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) (GridDynObject)0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  double *arg4 = (double *) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = *(double **)&jarg4; 
  result = (griddyn_status)gridDynObjectGetValueUnits(arg1,(char const *)arg2,(char const *)arg3,arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectGetFlag(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3) {
  jint jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) (GridDynObject)0 ;
  char *arg2 = (char *) 0 ;
  int *arg3 = (int *) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = *(int **)&jarg3; 
  result = (griddyn_status)gridDynObjectGetFlag(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectFind(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) (GridDynObject)0 ;
  char *arg2 = (char *) 0 ;
  GridDynObject result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (GridDynObject)gridDynObjectFind(arg1,(char const *)arg2);
  *(GridDynObject *)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectGetSubObject(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3) {
  jlong jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) (GridDynObject)0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  GridDynObject result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (int)jarg3; 
  result = (GridDynObject)gridDynObjectGetSubObject(arg1,(char const *)arg2,arg3);
  *(GridDynObject *)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectFindByUserId(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3) {
  jlong jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) (GridDynObject)0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  GridDynObject result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (int)jarg3; 
  result = (GridDynObject)gridDynObjectFindByUserId(arg1,(char const *)arg2,arg3);
  *(GridDynObject *)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectGetParent(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) (GridDynObject)0 ;
  GridDynObject result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  result = (GridDynObject)gridDynObjectGetParent(arg1);
  *(GridDynObject *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectGetType(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) (GridDynObject)0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  result = (char *)gridDynObjectGetType(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationCreate(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  GridDynSimulation result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (GridDynSimulation)gridDynSimulationCreate((char const *)arg1,(char const *)arg2);
  *(GridDynSimulation *)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationFree(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  gridDynSimulationFree(arg1);
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationInitializeFromString(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jint jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  char *arg2 = (char *) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (griddyn_status)gridDynSimulationInitializeFromString(arg1,(char const *)arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationInitializeFromArgs(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jint jarg4) {
  jint jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  int arg2 ;
  char **arg3 ;
  int arg4 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(char ***)&jarg3; 
  arg4 = (int)jarg4; 
  result = (griddyn_status)gridDynSimulationInitializeFromArgs(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationLoadfile(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3) {
  jint jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (griddyn_status)gridDynSimulationLoadfile(arg1,(char const *)arg2,(char const *)arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationAddCommand(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jint jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  char *arg2 = (char *) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (griddyn_status)gridDynSimulationAddCommand(arg1,(char const *)arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationPowerflowInitialize(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  result = (griddyn_status)gridDynSimulationPowerflowInitialize(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationPowerflow(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  result = (griddyn_status)gridDynSimulationPowerflow(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationDynamicInitialize(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  result = (griddyn_status)gridDynSimulationDynamicInitialize(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationReset(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  result = (griddyn_status)gridDynSimulationReset(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationGetCurrentTime(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jdouble jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  result = (double)gridDynSimulationGetCurrentTime(arg1);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationRun(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  result = (griddyn_status)gridDynSimulationRun(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationRunTo(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2) {
  jint jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  double arg2 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  arg2 = (double)jarg2; 
  result = (griddyn_status)gridDynSimulationRunTo(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationStep(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  result = (griddyn_status)gridDynSimulationStep(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationRunAsync(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  result = (griddyn_status)gridDynSimulationRunAsync(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationRunToAsync(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2) {
  jint jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  double arg2 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  arg2 = (double)jarg2; 
  result = (griddyn_status)gridDynSimulationRunToAsync(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationStepAsync(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  result = (griddyn_status)gridDynSimulationStepAsync(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationGetStatus(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  result = (int)gridDynSimulationGetStatus(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_getSimulationObject(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  GridDynObject result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  result = (GridDynObject)getSimulationObject(arg1);
  *(GridDynObject *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationGetSolverKey(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  char *arg2 = (char *) 0 ;
  SolverKey result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (SolverKey)gridDynSimulationGetSolverKey(arg1,(char const *)arg2);
  *(SolverKey *)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_java_griddyn_griddynJNI_gridDynSolverKeyFree(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  SolverKey arg1 = (SolverKey) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SolverKey *)&jarg1; 
  gridDynSolverKeyFree(arg1);
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationStateSize(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  SolverKey arg2 = (SolverKey) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  arg2 = *(SolverKey *)&jarg2; 
  result = (int)gridDynSimulationStateSize(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationBusCount(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  result = (int)gridDynSimulationBusCount(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationLineCount(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  result = (int)gridDynSimulationLineCount(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationGuessState(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  double arg2 ;
  double *arg3 = (double *) 0 ;
  double *arg4 = (double *) 0 ;
  SolverKey arg5 = (SolverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  arg2 = (double)jarg2; 
  arg3 = *(double **)&jarg3; 
  arg4 = *(double **)&jarg4; 
  arg5 = *(SolverKey *)&jarg5; 
  result = (griddyn_status)gridDynSimulationGuessState(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationSetState(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  double arg2 ;
  double *arg3 = (double *) 0 ;
  double *arg4 = (double *) 0 ;
  SolverKey arg5 = (SolverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  arg2 = (double)jarg2; 
  arg3 = *(double **)&jarg3; 
  arg4 = *(double **)&jarg4; 
  arg5 = *(SolverKey *)&jarg5; 
  result = (griddyn_status)gridDynSimulationSetState(arg1,arg2,(double const *)arg3,(double const *)arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationGetStateVariableTypes(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  double *arg2 = (double *) 0 ;
  SolverKey arg3 = (SolverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  arg2 = *(double **)&jarg2; 
  arg3 = *(SolverKey *)&jarg3; 
  result = (griddyn_status)gridDynSimulationGetStateVariableTypes(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationResidual(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jlong jarg6) {
  jint jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  double arg2 ;
  double *arg3 = (double *) 0 ;
  double *arg4 = (double *) 0 ;
  double *arg5 = (double *) 0 ;
  SolverKey arg6 = (SolverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  arg2 = (double)jarg2; 
  arg3 = *(double **)&jarg3; 
  arg4 = *(double **)&jarg4; 
  arg5 = *(double **)&jarg5; 
  arg6 = *(SolverKey *)&jarg6; 
  result = (griddyn_status)gridDynSimulationResidual(arg1,arg2,arg3,(double const *)arg4,(double const *)arg5,arg6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationDerivative(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  double arg2 ;
  double *arg3 = (double *) 0 ;
  double *arg4 = (double *) 0 ;
  SolverKey arg5 = (SolverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  arg2 = (double)jarg2; 
  arg3 = *(double **)&jarg3; 
  arg4 = *(double **)&jarg4; 
  arg5 = *(SolverKey *)&jarg5; 
  result = (griddyn_status)gridDynSimulationDerivative(arg1,arg2,arg3,(double const *)arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationAlgebraicUpdate(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2, jlong jarg3, jlong jarg4, jdouble jarg5, jlong jarg6) {
  jint jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  double arg2 ;
  double *arg3 = (double *) 0 ;
  double *arg4 = (double *) 0 ;
  double arg5 ;
  SolverKey arg6 = (SolverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  arg2 = (double)jarg2; 
  arg3 = *(double **)&jarg3; 
  arg4 = *(double **)&jarg4; 
  arg5 = (double)jarg5; 
  arg6 = *(SolverKey *)&jarg6; 
  result = (griddyn_status)gridDynSimulationAlgebraicUpdate(arg1,arg2,arg3,(double const *)arg4,arg5,arg6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSimulationJacobian(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2, jlong jarg3, jlong jarg4, jdouble jarg5, jlong jarg6, jlong jarg7) {
  jint jresult = 0 ;
  GridDynSimulation arg1 = (GridDynSimulation) 0 ;
  double arg2 ;
  double *arg3 = (double *) 0 ;
  double *arg4 = (double *) 0 ;
  double arg5 ;
  SolverKey arg6 = (SolverKey) 0 ;
  void (*arg7)(int,int,double) = (void (*)(int,int,double)) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSimulation *)&jarg1; 
  arg2 = (double)jarg2; 
  arg3 = *(double **)&jarg3; 
  arg4 = *(double **)&jarg4; 
  arg5 = (double)jarg5; 
  arg6 = *(SolverKey *)&jarg6; 
  arg7 = *(void (**)(int,int,double))&jarg7; 
  result = (griddyn_status)gridDynSimulationJacobian(arg1,arg2,(double const *)arg3,(double const *)arg4,arg5,arg6,arg7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_gridDynSingleQueryCreate(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) 0 ;
  char *arg2 = (char *) 0 ;
  GridDynSingleQuery result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (GridDynSingleQuery)gridDynSingleQueryCreate(arg1,(char const *)arg2);
  *(GridDynSingleQuery *)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_gridDynVectorQueryCreate(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) 0 ;
  char *arg2 = (char *) 0 ;
  GridDynVectorQuery result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (GridDynVectorQuery)gridDynVectorQueryCreate(arg1,(char const *)arg2);
  *(GridDynVectorQuery *)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_java_griddyn_griddynJNI_gridDynSingleQueryFree(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  GridDynSingleQuery arg1 = (GridDynSingleQuery) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSingleQuery *)&jarg1; 
  gridDynSingleQueryFree(arg1);
}


SWIGEXPORT void JNICALL Java_com_java_griddyn_griddynJNI_gridDynVectorQueryFree(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  GridDynVectorQuery arg1 = (GridDynVectorQuery) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynVectorQuery *)&jarg1; 
  gridDynVectorQueryFree(arg1);
}


SWIGEXPORT jdouble JNICALL Java_com_java_griddyn_griddynJNI_gridDynSingleQueryRun(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jdouble jresult = 0 ;
  GridDynSingleQuery arg1 = (GridDynSingleQuery) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSingleQuery *)&jarg1; 
  result = (double)gridDynSingleQueryRun(arg1);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynVectorQueryRun(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3) {
  jint jresult = 0 ;
  GridDynVectorQuery arg1 = (GridDynVectorQuery) 0 ;
  double *arg2 = (double *) 0 ;
  int arg3 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynVectorQuery *)&jarg1; 
  arg2 = *(double **)&jarg2; 
  arg3 = (int)jarg3; 
  result = (griddyn_status)gridDynVectorQueryRun(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynVectorQueryAppend(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jstring jarg3) {
  jint jresult = 0 ;
  GridDynVectorQuery arg1 = (GridDynVectorQuery) 0 ;
  GridDynObject arg2 = (GridDynObject) 0 ;
  char *arg3 = (char *) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynVectorQuery *)&jarg1; 
  arg2 = *(GridDynObject *)&jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (griddyn_status)gridDynVectorQueryAppend(arg1,arg2,(char const *)arg3);
  jresult = (jint)result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynSingleQueryUpdate(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jstring jarg3) {
  jint jresult = 0 ;
  GridDynSingleQuery arg1 = (GridDynSingleQuery) 0 ;
  GridDynObject arg2 = (GridDynObject) 0 ;
  char *arg3 = (char *) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynSingleQuery *)&jarg1; 
  arg2 = *(GridDynObject *)&jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (griddyn_status)gridDynSingleQueryUpdate(arg1,arg2,(char const *)arg3);
  jresult = (jint)result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynVectorQueryUpdate(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jstring jarg3) {
  jint jresult = 0 ;
  GridDynVectorQuery arg1 = (GridDynVectorQuery) 0 ;
  GridDynObject arg2 = (GridDynObject) 0 ;
  char *arg3 = (char *) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynVectorQuery *)&jarg1; 
  arg2 = *(GridDynObject *)&jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (griddyn_status)gridDynVectorQueryUpdate(arg1,arg2,(char const *)arg3);
  jresult = (jint)result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_java_griddyn_griddynJNI_gridDynEventCreate(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  GridDynObject arg2 = (GridDynObject) 0 ;
  GridDynEvent result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = *(GridDynObject *)&jarg2; 
  result = (GridDynEvent)gridDynEventCreate((char const *)arg1,arg2);
  *(GridDynEvent *)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_java_griddyn_griddynJNI_gridDynEventFree(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  GridDynEvent arg1 = (GridDynEvent) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynEvent *)&jarg1; 
  gridDynEventFree(arg1);
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynEventTrigger(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  GridDynEvent arg1 = (GridDynEvent) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynEvent *)&jarg1; 
  result = (griddyn_status)gridDynEventTrigger(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynEventSchedule(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  GridDynEvent arg1 = (GridDynEvent) 0 ;
  GridDynSimulation arg2 = (GridDynSimulation) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynEvent *)&jarg1; 
  arg2 = *(GridDynSimulation *)&jarg2; 
  result = (griddyn_status)gridDynEventSchedule(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynEventSetValue(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jdouble jarg3) {
  jint jresult = 0 ;
  GridDynEvent arg1 = (GridDynEvent) 0 ;
  char *arg2 = (char *) 0 ;
  double arg3 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynEvent *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (double)jarg3; 
  result = (griddyn_status)gridDynEventSetValue(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynEventSetString(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3) {
  jint jresult = 0 ;
  GridDynEvent arg1 = (GridDynEvent) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynEvent *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (griddyn_status)gridDynEventSetString(arg1,(char const *)arg2,(char const *)arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynEventSetFlag(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3) {
  jint jresult = 0 ;
  GridDynEvent arg1 = (GridDynEvent) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynEvent *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (int)jarg3; 
  result = (griddyn_status)gridDynEventSetFlag(arg1,(char const *)arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynEventSetTarget(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  GridDynEvent arg1 = (GridDynEvent) 0 ;
  GridDynObject arg2 = (GridDynObject) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynEvent *)&jarg1; 
  arg2 = *(GridDynObject *)&jarg2; 
  result = (griddyn_status)gridDynEventSetTarget(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectStateSize(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) 0 ;
  SolverKey arg2 = (SolverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  arg2 = *(SolverKey *)&jarg2; 
  result = (griddyn_status)gridDynObjectStateSize(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectGuessState(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) 0 ;
  double arg2 ;
  double *arg3 = (double *) 0 ;
  double *arg4 = (double *) 0 ;
  SolverKey arg5 = (SolverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  arg2 = (double)jarg2; 
  arg3 = *(double **)&jarg3; 
  arg4 = *(double **)&jarg4; 
  arg5 = *(SolverKey *)&jarg5; 
  result = (griddyn_status)gridDynObjectGuessState(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectSetState(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) 0 ;
  double arg2 ;
  double *arg3 = (double *) 0 ;
  double *arg4 = (double *) 0 ;
  SolverKey arg5 = (SolverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  arg2 = (double)jarg2; 
  arg3 = *(double **)&jarg3; 
  arg4 = *(double **)&jarg4; 
  arg5 = *(SolverKey *)&jarg5; 
  result = (griddyn_status)gridDynObjectSetState(arg1,arg2,(double const *)arg3,(double const *)arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectGetStateVariableTypes(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) 0 ;
  double *arg2 = (double *) 0 ;
  SolverKey arg3 = (SolverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  arg2 = *(double **)&jarg2; 
  arg3 = *(SolverKey *)&jarg3; 
  result = (griddyn_status)gridDynObjectGetStateVariableTypes(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectResidual(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) 0 ;
  double *arg2 = (double *) 0 ;
  int arg3 ;
  double *arg4 = (double *) 0 ;
  SolverKey arg5 = (SolverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  arg2 = *(double **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(double **)&jarg4; 
  arg5 = *(SolverKey *)&jarg5; 
  result = (griddyn_status)gridDynObjectResidual(arg1,(double const *)arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectDerivative(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) 0 ;
  double *arg2 = (double *) 0 ;
  int arg3 ;
  double *arg4 = (double *) 0 ;
  SolverKey arg5 = (SolverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  arg2 = *(double **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(double **)&jarg4; 
  arg5 = *(SolverKey *)&jarg5; 
  result = (griddyn_status)gridDynObjectDerivative(arg1,(double const *)arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectAlgebraicUpdate(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jlong jarg4, jdouble jarg5, jlong jarg6) {
  jint jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) 0 ;
  double *arg2 = (double *) 0 ;
  int arg3 ;
  double *arg4 = (double *) 0 ;
  double arg5 ;
  SolverKey arg6 = (SolverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  arg2 = *(double **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(double **)&jarg4; 
  arg5 = (double)jarg5; 
  arg6 = *(SolverKey *)&jarg6; 
  result = (griddyn_status)gridDynObjectAlgebraicUpdate(arg1,(double const *)arg2,arg3,arg4,arg5,arg6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectJacobian(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jdouble jarg4, jlong jarg5, jlong jarg6) {
  jint jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) 0 ;
  double *arg2 = (double *) 0 ;
  int arg3 ;
  double arg4 ;
  void (*arg5)(int,int,double) = (void (*)(int,int,double)) 0 ;
  SolverKey arg6 = (SolverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  arg2 = *(double **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (double)jarg4; 
  arg5 = *(void (**)(int,int,double))&jarg5; 
  arg6 = *(SolverKey *)&jarg6; 
  result = (griddyn_status)gridDynObjectJacobian(arg1,(double const *)arg2,arg3,arg4,arg5,arg6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectIoPartialDerivatives(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) 0 ;
  double *arg2 = (double *) 0 ;
  int arg3 ;
  void (*arg4)(int,int,double) = (void (*)(int,int,double)) 0 ;
  SolverKey arg5 = (SolverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  arg2 = *(double **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(void (**)(int,int,double))&jarg4; 
  arg5 = *(SolverKey *)&jarg5; 
  result = (griddyn_status)gridDynObjectIoPartialDerivatives(arg1,(double const *)arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_java_griddyn_griddynJNI_gridDynObjectOutputPartialDerivatives(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  GridDynObject arg1 = (GridDynObject) 0 ;
  double *arg2 = (double *) 0 ;
  int arg3 ;
  void (*arg4)(int,int,double) = (void (*)(int,int,double)) 0 ;
  SolverKey arg5 = (SolverKey) 0 ;
  griddyn_status result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(GridDynObject *)&jarg1; 
  arg2 = *(double **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(void (**)(int,int,double))&jarg4; 
  arg5 = *(SolverKey *)&jarg5; 
  result = (griddyn_status)gridDynObjectOutputPartialDerivatives(arg1,(double const *)arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

