/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.java.griddyn;

public class griddynJNI {
  static {
    System.loadLibrary("JNIgriddynd");
  }
  public final static native long new_doublep();
  public final static native long copy_doublep(double jarg1);
  public final static native void delete_doublep(long jarg1);
  public final static native void doublep_assign(long jarg1, double jarg2);
  public final static native double doublep_value(long jarg1);
  public final static native String new_charp();
  public final static native String copy_charp(char jarg1);
  public final static native void delete_charp(String jarg1);
  public final static native void charp_assign(String jarg1, char jarg2);
  public final static native char charp_value(String jarg1);
  public final static native long new_doubleArray(int jarg1);
  public final static native void delete_doubleArray(long jarg1);
  public final static native double doubleArray_getitem(long jarg1, doubleArray jarg1_, int jarg2);
  public final static native void doubleArray_setitem(long jarg1, doubleArray jarg1_, int jarg2, double jarg3);
  public final static native long doubleArray_cast(long jarg1, doubleArray jarg1_);
  public final static native long doubleArray_frompointer(long jarg1);
  public final static native int gridDynSimulationGetResults__SWIG_0(long jarg1, String jarg2, long jarg3, int jarg4);
  public final static native int griddyn_ok_get();
  public final static native int griddyn_invalid_object_get();
  public final static native int griddyn_invalid_parameter_value_get();
  public final static native int griddyn_unknown_parameter_get();
  public final static native int griddyn_add_failure_get();
  public final static native int griddyn_remove_failure_get();
  public final static native int griddyn_query_load_failure_get();
  public final static native int griddyn_file_load_failure_get();
  public final static native int griddyn_solve_error_get();
  public final static native int griddyn_object_not_initialized_get();
  public final static native int griddyn_invalid_function_call_get();
  public final static native int griddyn_function_failure_get();
  public final static native int GRIDDYN_PENDING_get();
  public final static native int GRIDDYN_COMPLETE_get();
  public final static native long gridDynObjectCreate(String jarg1, String jarg2);
  public final static native long gridDynObjectClone(long jarg1);
  public final static native void gridDynObjectFree(long jarg1);
  public final static native int gridDynObjectAdd(long jarg1, long jarg2);
  public final static native int gridDynObjectRemove(long jarg1, long jarg2);
  public final static native int gridDynObjectSetString(long jarg1, String jarg2, String jarg3);
  public final static native int gridDynObjectSetValue(long jarg1, String jarg2, double jarg3);
  public final static native int gridDynObjectSetValueUnits(long jarg1, String jarg2, double jarg3, String jarg4);
  public final static native int gridDynObjectSetFlag(long jarg1, String jarg2, int jarg3);
  public final static native int gridDynObjectGetString(long jarg1, String jarg2, String jarg3, int jarg4);
  public final static native int gridDynObjectGetValue(long jarg1, String jarg2, long jarg3);
  public final static native int gridDynObjectGetValueUnits(long jarg1, String jarg2, String jarg3, long jarg4);
  public final static native int gridDynObjectGetFlag(long jarg1, String jarg2, long jarg3);
  public final static native long gridDynObjectFind(long jarg1, String jarg2);
  public final static native long gridDynObjectGetSubObject(long jarg1, String jarg2, int jarg3);
  public final static native long gridDynObjectFindByUserId(long jarg1, String jarg2, int jarg3);
  public final static native long gridDynObjectGetParent(long jarg1);
  public final static native String gridDynObjectGetType(long jarg1);
  public final static native long gridDynSimulationCreate(String jarg1, String jarg2);
  public final static native void gridDynSimulationFree(long jarg1);
  public final static native int gridDynSimulationInitializeFromString(long jarg1, String jarg2);
  public final static native int gridDynSimulationInitializeFromArgs(long jarg1, int jarg2, long jarg3, int jarg4);
  public final static native int gridDynSimulationLoadfile(long jarg1, String jarg2, String jarg3);
  public final static native int gridDynSimulationAddCommand(long jarg1, String jarg2);
  public final static native int gridDynSimulationPowerflowInitialize(long jarg1);
  public final static native int gridDynSimulationPowerflow(long jarg1);
  public final static native int gridDynSimulationDynamicInitialize(long jarg1);
  public final static native int gridDynSimulationReset(long jarg1);
  public final static native double gridDynSimulationGetCurrentTime(long jarg1);
  public final static native int gridDynSimulationRun(long jarg1);
  public final static native int gridDynSimulationRunTo(long jarg1, double jarg2);
  public final static native int gridDynSimulationStep(long jarg1);
  public final static native int gridDynSimulationRunAsync(long jarg1);
  public final static native int gridDynSimulationRunToAsync(long jarg1, double jarg2);
  public final static native int gridDynSimulationStepAsync(long jarg1);
  public final static native int gridDynSimulationGetStatus(long jarg1);
  public final static native long getSimulationObject(long jarg1);
  public final static native long gridDynSimulationGetSolverKey(long jarg1, String jarg2);
  public final static native void gridDynSolverKeyFree(long jarg1);
  public final static native int gridDynSimulationStateSize(long jarg1, long jarg2);
  public final static native int gridDynSimulationBusCount(long jarg1);
  public final static native int gridDynSimulationLineCount(long jarg1);
  public final static native int gridDynSimulationGuessState(long jarg1, double jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int gridDynSimulationSetState(long jarg1, double jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int gridDynSimulationGetStateVariableTypes(long jarg1, long jarg2, long jarg3);
  public final static native int gridDynSimulationResidual(long jarg1, double jarg2, long jarg3, long jarg4, long jarg5, long jarg6);
  public final static native int gridDynSimulationDerivative(long jarg1, double jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int gridDynSimulationAlgebraicUpdate(long jarg1, double jarg2, long jarg3, long jarg4, double jarg5, long jarg6);
  public final static native int gridDynSimulationJacobian(long jarg1, double jarg2, long jarg3, long jarg4, double jarg5, long jarg6, long jarg7);
  public final static native long gridDynSingleQueryCreate(long jarg1, String jarg2);
  public final static native long gridDynVectorQueryCreate(long jarg1, String jarg2);
  public final static native void gridDynSingleQueryFree(long jarg1);
  public final static native void gridDynVectorQueryFree(long jarg1);
  public final static native double gridDynSingleQueryRun(long jarg1);
  public final static native int gridDynVectorQueryRun(long jarg1, long jarg2, int jarg3);
  public final static native int gridDynVectorQueryAppend(long jarg1, long jarg2, String jarg3);
  public final static native int gridDynSingleQueryUpdate(long jarg1, long jarg2, String jarg3);
  public final static native int gridDynVectorQueryUpdate(long jarg1, long jarg2, String jarg3);
  public final static native long gridDynEventCreate(String jarg1, long jarg2);
  public final static native void gridDynEventFree(long jarg1);
  public final static native int gridDynEventTrigger(long jarg1);
  public final static native int gridDynEventSchedule(long jarg1, long jarg2);
  public final static native int gridDynEventSetValue(long jarg1, String jarg2, double jarg3);
  public final static native int gridDynEventSetString(long jarg1, String jarg2, String jarg3);
  public final static native int gridDynEventSetFlag(long jarg1, String jarg2, int jarg3);
  public final static native int gridDynEventSetTarget(long jarg1, long jarg2);
  public final static native int gridDynObjectStateSize(long jarg1, long jarg2);
  public final static native int gridDynObjectGuessState(long jarg1, double jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int gridDynObjectSetState(long jarg1, double jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int gridDynObjectGetStateVariableTypes(long jarg1, long jarg2, long jarg3);
  public final static native int gridDynObjectResidual(long jarg1, long jarg2, int jarg3, long jarg4, long jarg5);
  public final static native int gridDynObjectDerivative(long jarg1, long jarg2, int jarg3, long jarg4, long jarg5);
  public final static native int gridDynObjectAlgebraicUpdate(long jarg1, long jarg2, int jarg3, long jarg4, double jarg5, long jarg6);
  public final static native int gridDynObjectJacobian(long jarg1, long jarg2, int jarg3, double jarg4, long jarg5, long jarg6);
  public final static native int gridDynObjectIoPartialDerivatives(long jarg1, long jarg2, int jarg3, long jarg4, long jarg5);
  public final static native int gridDynObjectOutputPartialDerivatives(long jarg1, long jarg2, int jarg3, long jarg4, long jarg5);
}
