/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.java.griddyn;

public class griddyn implements griddynConstants {
  public static SWIGTYPE_p_double new_doublep() {
    long cPtr = griddynJNI.new_doublep();
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static SWIGTYPE_p_double copy_doublep(double value) {
    long cPtr = griddynJNI.copy_doublep(value);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static void delete_doublep(SWIGTYPE_p_double obj) {
    griddynJNI.delete_doublep(SWIGTYPE_p_double.getCPtr(obj));
  }

  public static void doublep_assign(SWIGTYPE_p_double obj, double value) {
    griddynJNI.doublep_assign(SWIGTYPE_p_double.getCPtr(obj), value);
  }

  public static double doublep_value(SWIGTYPE_p_double obj) {
    return griddynJNI.doublep_value(SWIGTYPE_p_double.getCPtr(obj));
  }

  public static String new_charp() {
    return griddynJNI.new_charp();
  }

  public static String copy_charp(char value) {
    return griddynJNI.copy_charp(value);
  }

  public static void delete_charp(String obj) {
    griddynJNI.delete_charp(obj);
  }

  public static void charp_assign(String obj, char value) {
    griddynJNI.charp_assign(obj, value);
  }

  public static char charp_value(String obj) {
    return griddynJNI.charp_value(obj);
  }

  public static int gridDynSimulation_getResults(SWIGTYPE_p_void sim, String datatype, SWIGTYPE_p_double data, int maxSize) {
    return griddynJNI.gridDynSimulation_getResults__SWIG_0(SWIGTYPE_p_void.getCPtr(sim), datatype, SWIGTYPE_p_double.getCPtr(data), maxSize);
  }

  public static SWIGTYPE_p_void gridDynObject_create(String componentType, String objectType) {
    long cPtr = griddynJNI.gridDynObject_create(componentType, objectType);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static SWIGTYPE_p_void gridDynObject_clone(SWIGTYPE_p_void obj) {
    long cPtr = griddynJNI.gridDynObject_clone(SWIGTYPE_p_void.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static void gridDynObject_free(SWIGTYPE_p_void obj) {
    griddynJNI.gridDynObject_free(SWIGTYPE_p_void.getCPtr(obj));
  }

  public static int gridDynObject_add(SWIGTYPE_p_void parentObject, SWIGTYPE_p_void objectToAdd) {
    return griddynJNI.gridDynObject_add(SWIGTYPE_p_void.getCPtr(parentObject), SWIGTYPE_p_void.getCPtr(objectToAdd));
  }

  public static int gridDynObject_remove(SWIGTYPE_p_void parentObject, SWIGTYPE_p_void objectToRemove) {
    return griddynJNI.gridDynObject_remove(SWIGTYPE_p_void.getCPtr(parentObject), SWIGTYPE_p_void.getCPtr(objectToRemove));
  }

  public static int gridDynObject_setString(SWIGTYPE_p_void obj, String parameter, String value) {
    return griddynJNI.gridDynObject_setString(SWIGTYPE_p_void.getCPtr(obj), parameter, value);
  }

  public static int gridDynObject_setValue(SWIGTYPE_p_void obj, String parameter, double value) {
    return griddynJNI.gridDynObject_setValue(SWIGTYPE_p_void.getCPtr(obj), parameter, value);
  }

  public static int gridDynObject_setValueUnits(SWIGTYPE_p_void obj, String parameter, double value, String units) {
    return griddynJNI.gridDynObject_setValueUnits(SWIGTYPE_p_void.getCPtr(obj), parameter, value, units);
  }

  public static int gridDynObject_setFlag(SWIGTYPE_p_void obj, String flag, int val) {
    return griddynJNI.gridDynObject_setFlag(SWIGTYPE_p_void.getCPtr(obj), flag, val);
  }

  public static int gridDynObject_getString(SWIGTYPE_p_void obj, String parameter, String value, int N) {
    return griddynJNI.gridDynObject_getString(SWIGTYPE_p_void.getCPtr(obj), parameter, value, N);
  }

  public static int gridDynObject_getValue(SWIGTYPE_p_void obj, String parameter, SWIGTYPE_p_double result) {
    return griddynJNI.gridDynObject_getValue(SWIGTYPE_p_void.getCPtr(obj), parameter, SWIGTYPE_p_double.getCPtr(result));
  }

  public static int gridDynObject_getValueUnits(SWIGTYPE_p_void obj, String parameter, String units, SWIGTYPE_p_double result) {
    return griddynJNI.gridDynObject_getValueUnits(SWIGTYPE_p_void.getCPtr(obj), parameter, units, SWIGTYPE_p_double.getCPtr(result));
  }

  public static int gridDynObject_getFlag(SWIGTYPE_p_void obj, String flag, SWIGTYPE_p_int result) {
    return griddynJNI.gridDynObject_getFlag(SWIGTYPE_p_void.getCPtr(obj), flag, SWIGTYPE_p_int.getCPtr(result));
  }

  public static SWIGTYPE_p_void gridDynObject_find(SWIGTYPE_p_void obj, String objectToFind) {
    long cPtr = griddynJNI.gridDynObject_find(SWIGTYPE_p_void.getCPtr(obj), objectToFind);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static SWIGTYPE_p_void gridDynObject_getSubObject(SWIGTYPE_p_void obj, String componentType, int N) {
    long cPtr = griddynJNI.gridDynObject_getSubObject(SWIGTYPE_p_void.getCPtr(obj), componentType, N);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static SWIGTYPE_p_void gridDynObject_findByUserId(SWIGTYPE_p_void obj, String componentType, int ID) {
    long cPtr = griddynJNI.gridDynObject_findByUserId(SWIGTYPE_p_void.getCPtr(obj), componentType, ID);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static SWIGTYPE_p_void gridDynObject_getParent(SWIGTYPE_p_void obj) {
    long cPtr = griddynJNI.gridDynObject_getParent(SWIGTYPE_p_void.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static String gridDynObject_getType(SWIGTYPE_p_void obj) {
    return griddynJNI.gridDynObject_getType(SWIGTYPE_p_void.getCPtr(obj));
  }

  public static SWIGTYPE_p_void gridDynSimulation_create(String type, String name) {
    long cPtr = griddynJNI.gridDynSimulation_create(type, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static void gridDynSimulation_free(SWIGTYPE_p_void sim) {
    griddynJNI.gridDynSimulation_free(SWIGTYPE_p_void.getCPtr(sim));
  }

  public static int gridDynSimulation_initializeFromString(SWIGTYPE_p_void sim, String initializationString) {
    return griddynJNI.gridDynSimulation_initializeFromString(SWIGTYPE_p_void.getCPtr(sim), initializationString);
  }

  public static int gridDynSimulation_initializeFromArgs(SWIGTYPE_p_void sim, int argc, SWIGTYPE_p_p_char argv, int ignoreUnrecognized) {
    return griddynJNI.gridDynSimulation_initializeFromArgs(SWIGTYPE_p_void.getCPtr(sim), argc, SWIGTYPE_p_p_char.getCPtr(argv), ignoreUnrecognized);
  }

  public static int gridDynSimulation_loadfile(SWIGTYPE_p_void sim, String fileName, String fileType) {
    return griddynJNI.gridDynSimulation_loadfile(SWIGTYPE_p_void.getCPtr(sim), fileName, fileType);
  }

  public static int gridDynSimulation_addCommand(SWIGTYPE_p_void sim, String command) {
    return griddynJNI.gridDynSimulation_addCommand(SWIGTYPE_p_void.getCPtr(sim), command);
  }

  public static int gridDynSimulation_powerflowInitialize(SWIGTYPE_p_void sim) {
    return griddynJNI.gridDynSimulation_powerflowInitialize(SWIGTYPE_p_void.getCPtr(sim));
  }

  public static int gridDynSimulation_powerflow(SWIGTYPE_p_void sim) {
    return griddynJNI.gridDynSimulation_powerflow(SWIGTYPE_p_void.getCPtr(sim));
  }

  public static int gridDynSimulation_dynamicInitialize(SWIGTYPE_p_void sim) {
    return griddynJNI.gridDynSimulation_dynamicInitialize(SWIGTYPE_p_void.getCPtr(sim));
  }

  public static int gridDynSimulation_reset(SWIGTYPE_p_void sim) {
    return griddynJNI.gridDynSimulation_reset(SWIGTYPE_p_void.getCPtr(sim));
  }

  public static double gridDynSimulation_getCurrentTime(SWIGTYPE_p_void sim) {
    return griddynJNI.gridDynSimulation_getCurrentTime(SWIGTYPE_p_void.getCPtr(sim));
  }

  public static int gridDynSimulation_run(SWIGTYPE_p_void sim) {
    return griddynJNI.gridDynSimulation_run(SWIGTYPE_p_void.getCPtr(sim));
  }

  public static int gridDynSimulation_runTo(SWIGTYPE_p_void sim, double runToTime) {
    return griddynJNI.gridDynSimulation_runTo(SWIGTYPE_p_void.getCPtr(sim), runToTime);
  }

  public static int gridDynSimulation_Step(SWIGTYPE_p_void sim) {
    return griddynJNI.gridDynSimulation_Step(SWIGTYPE_p_void.getCPtr(sim));
  }

  public static int gridDynSimulation_runAsync(SWIGTYPE_p_void sim) {
    return griddynJNI.gridDynSimulation_runAsync(SWIGTYPE_p_void.getCPtr(sim));
  }

  public static int gridDynSimulation_runToAsync(SWIGTYPE_p_void sim, double runToTime) {
    return griddynJNI.gridDynSimulation_runToAsync(SWIGTYPE_p_void.getCPtr(sim), runToTime);
  }

  public static int gridDynSimulation_StepAsync(SWIGTYPE_p_void sim) {
    return griddynJNI.gridDynSimulation_StepAsync(SWIGTYPE_p_void.getCPtr(sim));
  }

  public static int gridDynSimulation_getStatus(SWIGTYPE_p_void sim) {
    return griddynJNI.gridDynSimulation_getStatus(SWIGTYPE_p_void.getCPtr(sim));
  }

  public static SWIGTYPE_p_void getSimulationObject(SWIGTYPE_p_void sim) {
    long cPtr = griddynJNI.getSimulationObject(SWIGTYPE_p_void.getCPtr(sim));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static SWIGTYPE_p_void gridDynSimulation_getSolverKey(SWIGTYPE_p_void sim, String solverType) {
    long cPtr = griddynJNI.gridDynSimulation_getSolverKey(SWIGTYPE_p_void.getCPtr(sim), solverType);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static void gridDynSolverKey_free(SWIGTYPE_p_void key) {
    griddynJNI.gridDynSolverKey_free(SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynSimulation_stateSize(SWIGTYPE_p_void sim, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynSimulation_stateSize(SWIGTYPE_p_void.getCPtr(sim), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynSimulation_busCount(SWIGTYPE_p_void sim) {
    return griddynJNI.gridDynSimulation_busCount(SWIGTYPE_p_void.getCPtr(sim));
  }

  public static int gridDynSimulation_lineCount(SWIGTYPE_p_void sim) {
    return griddynJNI.gridDynSimulation_lineCount(SWIGTYPE_p_void.getCPtr(sim));
  }

  public static int gridDynSimulation_guessState(SWIGTYPE_p_void sim, double time, SWIGTYPE_p_double states, SWIGTYPE_p_double dstate_dt, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynSimulation_guessState(SWIGTYPE_p_void.getCPtr(sim), time, SWIGTYPE_p_double.getCPtr(states), SWIGTYPE_p_double.getCPtr(dstate_dt), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynSimulation_setState(SWIGTYPE_p_void sim, double time, SWIGTYPE_p_double states, SWIGTYPE_p_double dstate_dt, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynSimulation_setState(SWIGTYPE_p_void.getCPtr(sim), time, SWIGTYPE_p_double.getCPtr(states), SWIGTYPE_p_double.getCPtr(dstate_dt), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynSimulation_getStateVariableTypes(SWIGTYPE_p_void sim, SWIGTYPE_p_double types, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynSimulation_getStateVariableTypes(SWIGTYPE_p_void.getCPtr(sim), SWIGTYPE_p_double.getCPtr(types), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynSimulation_residual(SWIGTYPE_p_void sim, double time, SWIGTYPE_p_double resid, SWIGTYPE_p_double states, SWIGTYPE_p_double dstate_dt, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynSimulation_residual(SWIGTYPE_p_void.getCPtr(sim), time, SWIGTYPE_p_double.getCPtr(resid), SWIGTYPE_p_double.getCPtr(states), SWIGTYPE_p_double.getCPtr(dstate_dt), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynSimulation_derivative(SWIGTYPE_p_void sim, double time, SWIGTYPE_p_double deriv, SWIGTYPE_p_double states, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynSimulation_derivative(SWIGTYPE_p_void.getCPtr(sim), time, SWIGTYPE_p_double.getCPtr(deriv), SWIGTYPE_p_double.getCPtr(states), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynSimulation_algebraicUpdate(SWIGTYPE_p_void sim, double time, SWIGTYPE_p_double update, SWIGTYPE_p_double states, double alpha, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynSimulation_algebraicUpdate(SWIGTYPE_p_void.getCPtr(sim), time, SWIGTYPE_p_double.getCPtr(update), SWIGTYPE_p_double.getCPtr(states), alpha, SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynSimulation_jacobian(SWIGTYPE_p_void sim, double time, SWIGTYPE_p_double states, SWIGTYPE_p_double dstate_dt, double cj, SWIGTYPE_p_void key, SWIGTYPE_p_f_int_int_double__void insert) {
    return griddynJNI.gridDynSimulation_jacobian(SWIGTYPE_p_void.getCPtr(sim), time, SWIGTYPE_p_double.getCPtr(states), SWIGTYPE_p_double.getCPtr(dstate_dt), cj, SWIGTYPE_p_void.getCPtr(key), SWIGTYPE_p_f_int_int_double__void.getCPtr(insert));
  }

  public static SWIGTYPE_p_void gridDynSingleQuery_create(SWIGTYPE_p_void obj, String queryString) {
    long cPtr = griddynJNI.gridDynSingleQuery_create(SWIGTYPE_p_void.getCPtr(obj), queryString);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static SWIGTYPE_p_void gridDynVectorQuery_create(SWIGTYPE_p_void obj, String queryString) {
    long cPtr = griddynJNI.gridDynVectorQuery_create(SWIGTYPE_p_void.getCPtr(obj), queryString);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static void gridDynSingleQuery_free(SWIGTYPE_p_void query) {
    griddynJNI.gridDynSingleQuery_free(SWIGTYPE_p_void.getCPtr(query));
  }

  public static void gridDynVectorQuery_free(SWIGTYPE_p_void query) {
    griddynJNI.gridDynVectorQuery_free(SWIGTYPE_p_void.getCPtr(query));
  }

  public static double gridDynSingleQuery_run(SWIGTYPE_p_void query) {
    return griddynJNI.gridDynSingleQuery_run(SWIGTYPE_p_void.getCPtr(query));
  }

  public static int gridDynVectorQuery_run(SWIGTYPE_p_void query, SWIGTYPE_p_double data, int N) {
    return griddynJNI.gridDynVectorQuery_run(SWIGTYPE_p_void.getCPtr(query), SWIGTYPE_p_double.getCPtr(data), N);
  }

  public static int gridDynVectorQuery_append(SWIGTYPE_p_void query, SWIGTYPE_p_void obj, String queryString) {
    return griddynJNI.gridDynVectorQuery_append(SWIGTYPE_p_void.getCPtr(query), SWIGTYPE_p_void.getCPtr(obj), queryString);
  }

  public static int gridDynSingleQuery_update(SWIGTYPE_p_void query, SWIGTYPE_p_void obj, String queryString) {
    return griddynJNI.gridDynSingleQuery_update(SWIGTYPE_p_void.getCPtr(query), SWIGTYPE_p_void.getCPtr(obj), queryString);
  }

  public static int gridDynVectorQuery_update(SWIGTYPE_p_void query, SWIGTYPE_p_void obj, String queryString) {
    return griddynJNI.gridDynVectorQuery_update(SWIGTYPE_p_void.getCPtr(query), SWIGTYPE_p_void.getCPtr(obj), queryString);
  }

  public static SWIGTYPE_p_void gridDynEvent_create(String eventString, SWIGTYPE_p_void obj) {
    long cPtr = griddynJNI.gridDynEvent_create(eventString, SWIGTYPE_p_void.getCPtr(obj));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static void gridDynEvent_free(SWIGTYPE_p_void evnt) {
    griddynJNI.gridDynEvent_free(SWIGTYPE_p_void.getCPtr(evnt));
  }

  public static int gridDynEvent_trigger(SWIGTYPE_p_void evnt) {
    return griddynJNI.gridDynEvent_trigger(SWIGTYPE_p_void.getCPtr(evnt));
  }

  public static int gridDynEvent_schedule(SWIGTYPE_p_void evnt, SWIGTYPE_p_void sim) {
    return griddynJNI.gridDynEvent_schedule(SWIGTYPE_p_void.getCPtr(evnt), SWIGTYPE_p_void.getCPtr(sim));
  }

  public static int gridDynEvent_setValue(SWIGTYPE_p_void evnt, String parameter, double value) {
    return griddynJNI.gridDynEvent_setValue(SWIGTYPE_p_void.getCPtr(evnt), parameter, value);
  }

  public static int gridDynEvent_setString(SWIGTYPE_p_void evnt, String parameter, String value) {
    return griddynJNI.gridDynEvent_setString(SWIGTYPE_p_void.getCPtr(evnt), parameter, value);
  }

  public static int gridDynEvent_setFlag(SWIGTYPE_p_void evnt, String flag, int val) {
    return griddynJNI.gridDynEvent_setFlag(SWIGTYPE_p_void.getCPtr(evnt), flag, val);
  }

  public static int gridDynEvent_setTarget(SWIGTYPE_p_void evnt, SWIGTYPE_p_void obj) {
    return griddynJNI.gridDynEvent_setTarget(SWIGTYPE_p_void.getCPtr(evnt), SWIGTYPE_p_void.getCPtr(obj));
  }

  public static int gridDynObject_stateSize(SWIGTYPE_p_void obj, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynObject_stateSize(SWIGTYPE_p_void.getCPtr(obj), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynObject_guessState(SWIGTYPE_p_void obj, double time, SWIGTYPE_p_double states, SWIGTYPE_p_double dstate_dt, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynObject_guessState(SWIGTYPE_p_void.getCPtr(obj), time, SWIGTYPE_p_double.getCPtr(states), SWIGTYPE_p_double.getCPtr(dstate_dt), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynObject_setState(SWIGTYPE_p_void obj, double time, SWIGTYPE_p_double states, SWIGTYPE_p_double dstate_dt, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynObject_setState(SWIGTYPE_p_void.getCPtr(obj), time, SWIGTYPE_p_double.getCPtr(states), SWIGTYPE_p_double.getCPtr(dstate_dt), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynObject_getStateVariableTypes(SWIGTYPE_p_void obj, SWIGTYPE_p_double types, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynObject_getStateVariableTypes(SWIGTYPE_p_void.getCPtr(obj), SWIGTYPE_p_double.getCPtr(types), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynObject_residual(SWIGTYPE_p_void obj, SWIGTYPE_p_double inputs, int inputSize, SWIGTYPE_p_double resid, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynObject_residual(SWIGTYPE_p_void.getCPtr(obj), SWIGTYPE_p_double.getCPtr(inputs), inputSize, SWIGTYPE_p_double.getCPtr(resid), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynObject_derivative(SWIGTYPE_p_void obj, SWIGTYPE_p_double inputs, int inputSize, SWIGTYPE_p_double deriv, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynObject_derivative(SWIGTYPE_p_void.getCPtr(obj), SWIGTYPE_p_double.getCPtr(inputs), inputSize, SWIGTYPE_p_double.getCPtr(deriv), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynObject_algebraicUpdate(SWIGTYPE_p_void obj, SWIGTYPE_p_double inputs, int inputSize, SWIGTYPE_p_double update, double alpha, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynObject_algebraicUpdate(SWIGTYPE_p_void.getCPtr(obj), SWIGTYPE_p_double.getCPtr(inputs), inputSize, SWIGTYPE_p_double.getCPtr(update), alpha, SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynObject_jacobian(SWIGTYPE_p_void obj, SWIGTYPE_p_double inputs, int inputSize, double cj, SWIGTYPE_p_f_int_int_double__void insert, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynObject_jacobian(SWIGTYPE_p_void.getCPtr(obj), SWIGTYPE_p_double.getCPtr(inputs), inputSize, cj, SWIGTYPE_p_f_int_int_double__void.getCPtr(insert), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynObject_ioPartialDerivatives(SWIGTYPE_p_void obj, SWIGTYPE_p_double inputs, int inputSize, SWIGTYPE_p_f_int_int_double__void insert, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynObject_ioPartialDerivatives(SWIGTYPE_p_void.getCPtr(obj), SWIGTYPE_p_double.getCPtr(inputs), inputSize, SWIGTYPE_p_f_int_int_double__void.getCPtr(insert), SWIGTYPE_p_void.getCPtr(key));
  }

  public static int gridDynObject_outputPartialDerivatives(SWIGTYPE_p_void obj, SWIGTYPE_p_double inputs, int inputSize, SWIGTYPE_p_f_int_int_double__void insert, SWIGTYPE_p_void key) {
    return griddynJNI.gridDynObject_outputPartialDerivatives(SWIGTYPE_p_void.getCPtr(obj), SWIGTYPE_p_double.getCPtr(inputs), inputSize, SWIGTYPE_p_f_int_int_double__void.getCPtr(insert), SWIGTYPE_p_void.getCPtr(key));
  }

}
