version: 2
aliases:
  - &setup_griddyn
    name: setup_griddyn
    environment:
    command: |
      mkdir -p build
      cd build
      eval cmake .. ${CMAKE_FLAGS}
      make -j 4

  - &run_griddyn_tests
    name: run_griddyn_tests
    command: |
      /root/project/scripts/run-circleci-tests.sh
      RESULT=$?
      exit $RESULT

jobs:
  build_gcc8:
    docker:
      - image: helics/buildenv:gcc8-builder
    environment:
      CMAKE_FLAGS: ' -DGRIDDYN_BUILD_TESTS=ON '
    steps:
      - checkout
      - run: *setup_griddyn
      - run: *run_griddyn_tests
  build_gcc7:
    docker:
      - image: helics/buildenv:gcc7-builder
    environment:
      CMAKE_FLAGS: ' -DGRIDDYN_BUILD_TESTS=ON '
    steps:
      - checkout
      - run: *setup_griddyn
      - run: *run_griddyn_tests
  build_clang9:
    docker:
      - image: helics/buildenv:clang9-builder
    environment:
      CMAKE_FLAGS: ' -DGRIDDYN_BUILD_TESTS=ON '
    steps:
      - checkout
      - run: *setup_griddyn
      - run: *run_griddyn_tests

workflows:
  version: 2
  griddyn_test:
    jobs:
      - build_gcc8
      - build_gcc7
