version: 2
aliases:

  - &setup_griddyn
    name: setup_griddyn
    environment:
    command: |
      apt update
      apt install -y libboost-all-dev
      mkdir -p build
      cd build
      eval cmake .. ${CMAKE_FLAGS}
      make -j 4

jobs:
  build_gcc8:
    docker:
      - image: helics/buildenv:gcc8-builder
    environment:
      CMAKE_FLAGS: " -DGRIDDYN_BUILD_TESTS=ON "
    steps:
      - checkout
      - run: *setup_griddyn

workflows:
  version: 2
  griddyn_test:
    jobs:
      - build_gcc8


