/*
 * Copyright (c) 2014-2026, Lawrence Livermore National Security
 * See the top-level NOTICE for additional details. All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 */

#pragma once

// include the autogenerated config file

#include "coreObject.h"
#include <string>
#include <string_view>
#include <vector>

#include <boost/multi_index/member.hpp>
#include <boost/multi_index/ordered_index.hpp>
#include <boost/multi_index_container.hpp>

namespace griddyn {
using boost::multi_index_container;

struct name {};
struct id {};
struct uid {};

struct objectRecord {
    coreObject* object = nullptr;
    id_type_t objectID = 0;
    std::string objectName;
    index_t userID = 0;

    objectRecord() = default;
    explicit objectRecord(coreObject* obj):
        object(obj), objectID(obj->getID()), objectName(obj->getName()), userID(obj->getUserID())
    {
    }
};
// define a multi-index container based on the object id, which should be unique, and the name which
// also should be unique, and the user id, which isn't necessarily unique.
using objectIndex = multi_index_container<
    objectRecord,
    boost::multi_index::indexed_by<
        boost::multi_index::
            ordered_unique<boost::multi_index::tag<id>,
                           boost::multi_index::member<objectRecord, id_type_t, &objectRecord::objectID>>,
        boost::multi_index::ordered_unique<
            boost::multi_index::tag<name>,
            boost::multi_index::member<objectRecord, std::string, &objectRecord::objectName>>,
        boost::multi_index::ordered_non_unique<
            boost::multi_index::tag<uid>,
            boost::multi_index::member<objectRecord, index_t, &objectRecord::userID>>>>;

/** @brief list class that facilitates adding or searching for pointers to griddyn by name or id
 * a list class that stores a list of the objects contained in an unordered map to facilitate
 * searching for objects
 */
class coreObjectList {
  private:
    objectIndex m_objects;  //!< the object map structure
  public:
    /** @brief default constructor*/
    coreObjectList() = default;
    /**
     * @brief function to insert an object into the class
     * @param[in] obj the object to insert
     * @param[in] replace an optional indicator telling whether to replace the object or nor
     * @return a bool indicating successful insertion
     */
    bool insert(coreObject* obj, bool replace = false);
    /** @brief remove an object
     * function to remove an object from the container
     * @param[in] obj the object to insert
     * @return a bool indicating successful removal (0 on success, -1 on failure) const
     */
    bool remove(coreObject* obj);
    /** @brief remove an object by name
     * function to remove an object from the container
     * @param[in] objName the name of the object to remove
     * @return a bool indicating successful removal (0 on success, -1 on failure) const
     */
    bool remove(std::string_view objName);

    /** @brief find object by name
     * function to find an object by name
     * @param[in] objName the name of the object to search for
     * @return a pointer to the object if found otherwise nullptr
     */
    coreObject* find(std::string_view objName) const;

    /** @brief find object by id
     * function to find an object by user id code
     * @param[in] searchID the user id of the object to search for
     * @return a vector of objects with the appropriate searchID
     */
    std::vector<coreObject*> find(index_t searchID) const;

    /** @brief check if an object is already contained
     * function to find an object by id
     * @param[in] obj to check
     * @return a bool indicating if the object is a member or not
     */
    bool isMember(const coreObject* obj) const;

    /**
    * @brief deletes all object pointed to by the list
    calls the condDel
    */
    void deleteAll(coreObject* parent);

    /** @brief get the size of the list

    * @return the size of the list
    */
    count_t size() const { return static_cast<count_t>(m_objects.size()); }

    /**
    * @brief update a single object with a name change or index change
    @param[in] obj the object with the change
    */
    void updateObject(coreObject* obj);
};

}  // namespace griddyn
