/*
 * Copyright (c) 2014-2026, Lawrence Livermore National Security
 * See the top-level NOTICE for additional details. All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 */

#pragma once

// include the autogenerated config file

#include "coreObject.h"
#include <cstddef>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

namespace griddyn {

/** @brief list class that facilitates adding or searching for pointers to griddyn by name or id
 * a list class that stores a list of the objects contained in an unordered map to facilitate
 * searching for objects
 */
class coreObjectList {
  private:
    struct objectRecord {
        CoreObject* object = nullptr;
        std::string name;
        index_t userID = 0;
    };

    std::unordered_map<id_type_t, objectRecord> m_objectsById;  //!< primary object storage
    std::unordered_map<std::string, id_type_t> m_idsByName;  //!< name lookup index
    std::unordered_multimap<index_t, id_type_t> m_idsByUserId;  //!< user id lookup index

    void addIndexes(id_type_t objectID, const objectRecord& record);
    void removeIndexes(id_type_t objectID, const objectRecord& record);

  public:
    /** @brief default constructor*/
    coreObjectList() = default;
    /**
     * @brief function to insert an object into the class
     * @param[in] obj the object to insert
     * @param[in] replace an optional indicator telling whether to replace the object or nor
     * @return a bool indicating successful insertion
     */
    bool insert(CoreObject* obj, bool replace = false);
    /** @brief remove an object
     * function to remove an object from the container
     * @param[in] obj the object to insert
     * @return a bool indicating successful removal (0 on success, -1 on failure) const
     */
    bool remove(CoreObject* obj);
    /** @brief remove an object by name
     * function to remove an object from the container
     * @param[in] objName the name of the object to remove
     * @return a bool indicating successful removal (0 on success, -1 on failure) const
     */
    bool remove(std::string_view objName);

    /** @brief find object by name
     * function to find an object by name
     * @param[in] objName the name of the object to search for
     * @return a pointer to the object if found otherwise nullptr
     */
    CoreObject* find(std::string_view objName) const;

    /** @brief find object by id
     * function to find an object by user id code
     * @param[in] searchID the user id of the object to search for
     * @return a vector of objects with the appropriate searchID
     */
    std::vector<CoreObject*> find(index_t searchID) const;

    /** @brief check if an object is already contained
     * function to find an object by id
     * @param[in] obj to check
     * @return a bool indicating if the object is a member or not
     */
    bool isMember(const CoreObject* obj) const;

    /**
    * @brief deletes all object pointed to by the list
    calls the condDel
    */
    void deleteAll(CoreObject* parent);

    /** @brief get the size of the list

    * @return the size of the list
    */
    count_t size() const { return static_cast<count_t>(m_objectsById.size()); }

    /**
    * @brief update a single object with a name change or index change
    @param[in] obj the object with the change
    */
    void updateObject(CoreObject* obj);
};

}  // namespace griddyn

