# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.


from sys import version_info as _swig_python_version_info

if _swig_python_version_info >= (2, 7, 0):

    def swig_import_helper():
        import importlib

        pkg = __name__.rpartition(".")[0]
        mname = ".".join((pkg, "_griddyn")).lstrip(".")
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module("_griddyn")

    _griddyn = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):

    def swig_import_helper():
        from os.path import dirname
        import imp

        fp = None
        try:
            fp, pathname, description = imp.find_module("_griddyn", [dirname(__file__)])
        except ImportError:
            import _griddyn

            return _griddyn
        if fp is not None:
            try:
                _mod = imp.load_module("_griddyn", fp, pathname, description)
            finally:
                fp.close()
            return _mod

    _griddyn = swig_import_helper()
    del swig_import_helper
else:
    import _griddyn
del _swig_python_version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if name == "thisown":
        return self.this.own(value)
    if name == "this":
        if type(value).__name__ == "SwigPyObject":
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if not static:
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if name == "thisown":
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (
        self.__class__.__module__,
        self.__class__.__name__,
        strthis,
    )


try:
    _object = object
    _newclass = 1
except __builtin__.Exception:

    class _object:
        pass

    _newclass = 0


def new_doublep():
    return _griddyn.new_doublep()


new_doublep = _griddyn.new_doublep


def copy_doublep(value):
    return _griddyn.copy_doublep(value)


copy_doublep = _griddyn.copy_doublep


def delete_doublep(obj):
    return _griddyn.delete_doublep(obj)


delete_doublep = _griddyn.delete_doublep


def doublep_assign(obj, value):
    return _griddyn.doublep_assign(obj, value)


doublep_assign = _griddyn.doublep_assign


def doublep_value(obj):
    return _griddyn.doublep_value(obj)


doublep_value = _griddyn.doublep_value


def new_charp():
    return _griddyn.new_charp()


new_charp = _griddyn.new_charp


def copy_charp(value):
    return _griddyn.copy_charp(value)


copy_charp = _griddyn.copy_charp


def delete_charp(obj):
    return _griddyn.delete_charp(obj)


delete_charp = _griddyn.delete_charp


def charp_assign(obj, value):
    return _griddyn.charp_assign(obj, value)


charp_assign = _griddyn.charp_assign


def charp_value(obj):
    return _griddyn.charp_value(obj)


charp_value = _griddyn.charp_value


class doubleArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, doubleArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, doubleArray, name)
    __repr__ = _swig_repr

    def __init__(self, nelements):
        this = _griddyn.new_doubleArray(nelements)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    __swig_destroy__ = _griddyn.delete_doubleArray
    __del__ = lambda self: None

    def __getitem__(self, index):
        return _griddyn.doubleArray___getitem__(self, index)

    def __setitem__(self, index, value):
        return _griddyn.doubleArray___setitem__(self, index, value)

    def cast(self):
        return _griddyn.doubleArray_cast(self)

    if _newclass:
        frompointer = staticmethod(_griddyn.doubleArray_frompointer)
    else:
        frompointer = _griddyn.doubleArray_frompointer


doubleArray_swigregister = _griddyn.doubleArray_swigregister
doubleArray_swigregister(doubleArray)


def doubleArray_frompointer(t):
    return _griddyn.doubleArray_frompointer(t)


doubleArray_frompointer = _griddyn.doubleArray_frompointer


class charArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, charArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, charArray, name)
    __repr__ = _swig_repr

    def __init__(self, nelements):
        this = _griddyn.new_charArray(nelements)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    __swig_destroy__ = _griddyn.delete_charArray
    __del__ = lambda self: None

    def __getitem__(self, index):
        return _griddyn.charArray___getitem__(self, index)

    def __setitem__(self, index, value):
        return _griddyn.charArray___setitem__(self, index, value)

    def cast(self):
        return _griddyn.charArray_cast(self)

    if _newclass:
        frompointer = staticmethod(_griddyn.charArray_frompointer)
    else:
        frompointer = _griddyn.charArray_frompointer


charArray_swigregister = _griddyn.charArray_swigregister
charArray_swigregister(charArray)


def charArray_frompointer(t):
    return _griddyn.charArray_frompointer(t)


charArray_frompointer = _griddyn.charArray_frompointer

EXECUTION_SUCCESS = _griddyn.EXECUTION_SUCCESS
INVALID_OBJECT = _griddyn.INVALID_OBJECT
INVALID_PARAMETER_VALUE = _griddyn.INVALID_PARAMETER_VALUE
UNKNOWN_PARAMETER = _griddyn.UNKNOWN_PARAMETER
ADD_FAILURE = _griddyn.ADD_FAILURE
REMOVE_FAILURE = _griddyn.REMOVE_FAILURE
QUERY_LOAD_FAILURE = _griddyn.QUERY_LOAD_FAILURE
FILE_LOAD_FAILURE = _griddyn.FILE_LOAD_FAILURE
SOLVE_ERROR = _griddyn.SOLVE_ERROR
OBJECT_NOT_INITIALIZED = _griddyn.OBJECT_NOT_INITIALIZED
INVALID_FUNCTION_CALL = _griddyn.INVALID_FUNCTION_CALL
GRIDDYN_PENDING = _griddyn.GRIDDYN_PENDING
GRIDDYN_COMPLETE = _griddyn.GRIDDYN_COMPLETE


gridDynObjectCreate = _griddyn.gridDynObjectCreate
gridDynObjectClone = _griddyn.gridDynObjectClone
gridDynObjectFree = _griddyn.gridDynObjectFree
gridDynObjectAdd = _griddyn.gridDynObjectAdd
gridDynObjectRemove = _griddyn.gridDynObjectRemove
gridDynObjectSetString = _griddyn.gridDynObjectSetString
gridDynObjectSetValue = _griddyn.gridDynObjectSetValue
gridDynObjectSetFlag = _griddyn.gridDynObjectSetFlag
gridDynObjectGetString = _griddyn.gridDynObjectGetString
gridDynObjectGetValue = _griddyn.gridDynObjectGetValue
gridDynObjectGetFlag = _griddyn.gridDynObjectGetFlag
gridDynObjectFind = _griddyn.gridDynObjectFind
gridDynObjectGetSubObject = _griddyn.gridDynObjectGetSubObject
gridDynObjectFindByUserId = _griddyn.gridDynObjectFindByUserId
gridDynObjectGetParent = _griddyn.gridDynObjectGetParent
gridDynObjectGetType = _griddyn.gridDynObjectGetType


gridDynSimulationCreate = _griddyn.gridDynSimulationCreate
gridDynSimulationFree = _griddyn.gridDynSimulationFree
gridDynSimulationInitializeFromString = _griddyn.gridDynSimulationInitializeFromString
gridDynSimulationInitializeFromArgs = _griddyn.gridDynSimulationInitializeFromArgs
gridDynSimulationLoadfile = _griddyn.gridDynSimulationLoadfile
gridDynSimulationAddCommand = _griddyn.gridDynSimulationAddCommand
gridDynSimulationPowerflowInitialize = _griddyn.gridDynSimulationPowerflowInitialize
gridDynSimulationPowerflow = _griddyn.gridDynSimulationPowerflow
gridDynSimulationDynamicInitialize = _griddyn.gridDynSimulationDynamicInitialize
gridDynSimulationReset = _griddyn.gridDynSimulationReset
gridDynSimulationGetCurrentTime = _griddyn.gridDynSimulationGetCurrentTime
gridDynSimulationRun = _griddyn.gridDynSimulationRun
gridDynSimulationRunTo = _griddyn.gridDynSimulationRunTo
gridDynSimulationStep = _griddyn.gridDynSimulationStep
gridDynSimulationRunAsync = _griddyn.gridDynSimulationRunAsync
gridDynSimulationRunToAsync = _griddyn.gridDynSimulationRunToAsync
gridDynSimulationStepAsync = _griddyn.gridDynSimulationStepAsync
gridDynSimulationGetStatus = _griddyn.gridDynSimulationGetStatus


def getSimulationObject(sim):
    return _griddyn.getSimulationObject(sim)


getSimulationObject = _griddyn.getSimulationObject


gridDynSimulationGetSolverKey = _griddyn.gridDynSimulationGetSolverKey
gridDynSolverKeyFree = _griddyn.gridDynSolverKeyFree
gridDynSimulationStateSize = _griddyn.gridDynSimulationStateSize
gridDynSimulationBusCount = _griddyn.gridDynSimulationBusCount
gridDynSimulationLineCount = _griddyn.gridDynSimulationLineCount
gridDynSimulationGetResults = _griddyn.gridDynSimulationGetResults
gridDynSimulationGuessState = _griddyn.gridDynSimulationGuessState
gridDynSimulationSetState = _griddyn.gridDynSimulationSetState
gridDynSimulationGetStateVariableTypes = _griddyn.gridDynSimulationGetStateVariableTypes
gridDynSimulationResidual = _griddyn.gridDynSimulationResidual
gridDynSimulationDerivative = _griddyn.gridDynSimulationDerivative
gridDynSimulationAlgebraicUpdate = _griddyn.gridDynSimulationAlgebraicUpdate
gridDynSimulationJacobian = _griddyn.gridDynSimulationJacobian
gridDynSingleQueryCreate = _griddyn.gridDynSingleQueryCreate
gridDynVectorQueryCreate = _griddyn.gridDynVectorQueryCreate
gridDynSingleQueryFree = _griddyn.gridDynSingleQueryFree
gridDynVectorQueryFree = _griddyn.gridDynVectorQueryFree
gridDynSingleQueryRun = _griddyn.gridDynSingleQueryRun
gridDynVectorQueryRun = _griddyn.gridDynVectorQueryRun
gridDynVectorQueryAppend = _griddyn.gridDynVectorQueryAppend
gridDynSingleQueryUpdate = _griddyn.gridDynSingleQueryUpdate
gridDynVectorQueryUpdate = _griddyn.gridDynVectorQueryUpdate
gridDynEventCreate = _griddyn.gridDynEventCreate
gridDynEventFree = _griddyn.gridDynEventFree
gridDynEventTrigger = _griddyn.gridDynEventTrigger
gridDynEventSchedule = _griddyn.gridDynEventSchedule
gridDynEventSetValue = _griddyn.gridDynEventSetValue
gridDynEventSetString = _griddyn.gridDynEventSetString
gridDynEventSetFlag = _griddyn.gridDynEventSetFlag
gridDynEventSetTarget = _griddyn.gridDynEventSetTarget
gridDynObjectStateSize = _griddyn.gridDynObjectStateSize
gridDynObjectGuessState = _griddyn.gridDynObjectGuessState
gridDynObjectSetState = _griddyn.gridDynObjectSetState
gridDynObjectGetStateVariableTypes = _griddyn.gridDynObjectGetStateVariableTypes
gridDynObjectResidual = _griddyn.gridDynObjectResidual
gridDynObjectDerivative = _griddyn.gridDynObjectDerivative
gridDynObjectAlgebraicUpdate = _griddyn.gridDynObjectAlgebraicUpdate
gridDynObjectJacobian = _griddyn.gridDynObjectJacobian
gridDynObjectIoPartialDerivatives = _griddyn.gridDynObjectIoPartialDerivatives
gridDynObjectOutputPartialDerivatives = _griddyn.gridDynObjectOutputPartialDerivatives
# This file is compatible with both classic and new-style classes.
