# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info

if _swig_python_version_info >= (2, 7, 0):

    def swig_import_helper():
        import importlib

        pkg = __name__.rpartition(".")[0]
        mname = ".".join((pkg, "_griddyn")).lstrip(".")
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module("_griddyn")

    _griddyn = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):

    def swig_import_helper():
        from os.path import dirname
        import imp

        fp = None
        try:
            fp, pathname, description = imp.find_module("_griddyn", [dirname(__file__)])
        except ImportError:
            import _griddyn

            return _griddyn
        try:
            _mod = imp.load_module("_griddyn", fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod

    _griddyn = swig_import_helper()
    del swig_import_helper
else:
    import _griddyn
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if name == "thisown":
        return self.this.own(value)
    if name == "this":
        if type(value).__name__ == "SwigPyObject":
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if not static:
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if name == "thisown":
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (
        self.__class__.__module__,
        self.__class__.__name__,
        strthis,
    )


try:
    _object = object
    _newclass = 1
except __builtin__.Exception:

    class _object:
        pass

    _newclass = 0


def new_doublep():
    return _griddyn.new_doublep()


new_doublep = _griddyn.new_doublep


def copy_doublep(value):
    return _griddyn.copy_doublep(value)


copy_doublep = _griddyn.copy_doublep


def delete_doublep(obj):
    return _griddyn.delete_doublep(obj)


delete_doublep = _griddyn.delete_doublep


def doublep_assign(obj, value):
    return _griddyn.doublep_assign(obj, value)


doublep_assign = _griddyn.doublep_assign


def doublep_value(obj):
    return _griddyn.doublep_value(obj)


doublep_value = _griddyn.doublep_value


def new_charp():
    return _griddyn.new_charp()


new_charp = _griddyn.new_charp


def copy_charp(value):
    return _griddyn.copy_charp(value)


copy_charp = _griddyn.copy_charp


def delete_charp(obj):
    return _griddyn.delete_charp(obj)


delete_charp = _griddyn.delete_charp


def charp_assign(obj, value):
    return _griddyn.charp_assign(obj, value)


charp_assign = _griddyn.charp_assign


def charp_value(obj):
    return _griddyn.charp_value(obj)


charp_value = _griddyn.charp_value


class doubleArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, doubleArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, doubleArray, name)
    __repr__ = _swig_repr

    def __init__(self, nelements):
        this = _griddyn.new_doubleArray(nelements)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    __swig_destroy__ = _griddyn.delete_doubleArray

    def __getitem__(self, index):
        return _griddyn.doubleArray___getitem__(self, index)

    def __setitem__(self, index, value):
        return _griddyn.doubleArray___setitem__(self, index, value)

    def cast(self):
        return _griddyn.doubleArray_cast(self)

    if _newclass:
        frompointer = staticmethod(_griddyn.doubleArray_frompointer)
    else:
        frompointer = _griddyn.doubleArray_frompointer


doubleArray_swigregister = _griddyn.doubleArray_swigregister
doubleArray_swigregister(doubleArray)


def doubleArray_frompointer(t):
    return _griddyn.doubleArray_frompointer(t)


doubleArray_frompointer = _griddyn.doubleArray_frompointer

griddyn_ok = _griddyn.griddyn_ok
griddyn_invalid_object = _griddyn.griddyn_invalid_object
griddyn_invalid_parameter_value = _griddyn.griddyn_invalid_parameter_value
griddyn_unknown_parameter = _griddyn.griddyn_unknown_parameter
griddyn_add_failure = _griddyn.griddyn_add_failure
griddyn_remove_failure = _griddyn.griddyn_remove_failure
griddyn_query_load_failure = _griddyn.griddyn_query_load_failure
griddyn_file_load_failure = _griddyn.griddyn_file_load_failure
griddyn_solve_error = _griddyn.griddyn_solve_error
griddyn_object_not_initialized = _griddyn.griddyn_object_not_initialized
griddyn_invalid_function_call = _griddyn.griddyn_invalid_function_call
griddyn_function_failure = _griddyn.griddyn_function_failure
GRIDDYN_PENDING = _griddyn.GRIDDYN_PENDING
GRIDDYN_COMPLETE = _griddyn.GRIDDYN_COMPLETE


def gridDynObjectCreate(componentType, objectType):
    return _griddyn.gridDynObjectCreate(componentType, objectType)


gridDynObjectCreate = _griddyn.gridDynObjectCreate


def gridDynObjectClone(obj):
    return _griddyn.gridDynObjectClone(obj)


gridDynObjectClone = _griddyn.gridDynObjectClone


def gridDynObjectFree(obj):
    return _griddyn.gridDynObjectFree(obj)


gridDynObjectFree = _griddyn.gridDynObjectFree


def gridDynObjectAdd(parentObject, objectToAdd):
    return _griddyn.gridDynObjectAdd(parentObject, objectToAdd)


gridDynObjectAdd = _griddyn.gridDynObjectAdd


def gridDynObjectRemove(parentObject, objectToRemove):
    return _griddyn.gridDynObjectRemove(parentObject, objectToRemove)


gridDynObjectRemove = _griddyn.gridDynObjectRemove


def gridDynObjectSetString(obj, parameter, value):
    return _griddyn.gridDynObjectSetString(obj, parameter, value)


gridDynObjectSetString = _griddyn.gridDynObjectSetString


def gridDynObjectSetValue(obj, parameter, value):
    return _griddyn.gridDynObjectSetValue(obj, parameter, value)


gridDynObjectSetValue = _griddyn.gridDynObjectSetValue


def gridDynObjectSetValueUnits(obj, parameter, value, units):
    return _griddyn.gridDynObjectSetValueUnits(obj, parameter, value, units)


gridDynObjectSetValueUnits = _griddyn.gridDynObjectSetValueUnits


def gridDynObjectSetFlag(obj, flag, val):
    return _griddyn.gridDynObjectSetFlag(obj, flag, val)


gridDynObjectSetFlag = _griddyn.gridDynObjectSetFlag


def gridDynObjectGetString(obj, parameter, value):
    return _griddyn.gridDynObjectGetString(obj, parameter, value)


gridDynObjectGetString = _griddyn.gridDynObjectGetString


def gridDynObjectGetValue(obj, parameter, result):
    return _griddyn.gridDynObjectGetValue(obj, parameter, result)


gridDynObjectGetValue = _griddyn.gridDynObjectGetValue


def gridDynObjectGetValueUnits(obj, parameter, units, result):
    return _griddyn.gridDynObjectGetValueUnits(obj, parameter, units, result)


gridDynObjectGetValueUnits = _griddyn.gridDynObjectGetValueUnits


def gridDynObjectGetFlag(obj, flag, result):
    return _griddyn.gridDynObjectGetFlag(obj, flag, result)


gridDynObjectGetFlag = _griddyn.gridDynObjectGetFlag


def gridDynObjectFind(obj, objectToFind):
    return _griddyn.gridDynObjectFind(obj, objectToFind)


gridDynObjectFind = _griddyn.gridDynObjectFind


def gridDynObjectGetSubObject(obj, componentType, N):
    return _griddyn.gridDynObjectGetSubObject(obj, componentType, N)


gridDynObjectGetSubObject = _griddyn.gridDynObjectGetSubObject


def gridDynObjectFindByUserId(obj, componentType, ID):
    return _griddyn.gridDynObjectFindByUserId(obj, componentType, ID)


gridDynObjectFindByUserId = _griddyn.gridDynObjectFindByUserId


def gridDynObjectGetParent(obj):
    return _griddyn.gridDynObjectGetParent(obj)


gridDynObjectGetParent = _griddyn.gridDynObjectGetParent


def gridDynObjectGetType(obj):
    return _griddyn.gridDynObjectGetType(obj)


gridDynObjectGetType = _griddyn.gridDynObjectGetType


def gridDynSimulationCreate(type, name):
    return _griddyn.gridDynSimulationCreate(type, name)


gridDynSimulationCreate = _griddyn.gridDynSimulationCreate


def gridDynSimulationFree(sim):
    return _griddyn.gridDynSimulationFree(sim)


gridDynSimulationFree = _griddyn.gridDynSimulationFree


def gridDynSimulationInitializeFromString(sim, initializationString):
    return _griddyn.gridDynSimulationInitializeFromString(sim, initializationString)


gridDynSimulationInitializeFromString = _griddyn.gridDynSimulationInitializeFromString


def gridDynSimulationInitializeFromArgs(sim, argc, argv, ignoreUnrecognized):
    return _griddyn.gridDynSimulationInitializeFromArgs(sim, argc, argv, ignoreUnrecognized)


gridDynSimulationInitializeFromArgs = _griddyn.gridDynSimulationInitializeFromArgs


def gridDynSimulationLoadfile(sim, fileName, fileType):
    return _griddyn.gridDynSimulationLoadfile(sim, fileName, fileType)


gridDynSimulationLoadfile = _griddyn.gridDynSimulationLoadfile


def gridDynSimulationAddCommand(sim, command):
    return _griddyn.gridDynSimulationAddCommand(sim, command)


gridDynSimulationAddCommand = _griddyn.gridDynSimulationAddCommand


def gridDynSimulationPowerflowInitialize(sim):
    return _griddyn.gridDynSimulationPowerflowInitialize(sim)


gridDynSimulationPowerflowInitialize = _griddyn.gridDynSimulationPowerflowInitialize


def gridDynSimulationPowerflow(sim):
    return _griddyn.gridDynSimulationPowerflow(sim)


gridDynSimulationPowerflow = _griddyn.gridDynSimulationPowerflow


def gridDynSimulationDynamicInitialize(sim):
    return _griddyn.gridDynSimulationDynamicInitialize(sim)


gridDynSimulationDynamicInitialize = _griddyn.gridDynSimulationDynamicInitialize


def gridDynSimulationReset(sim):
    return _griddyn.gridDynSimulationReset(sim)


gridDynSimulationReset = _griddyn.gridDynSimulationReset


def gridDynSimulationGetCurrentTime(sim):
    return _griddyn.gridDynSimulationGetCurrentTime(sim)


gridDynSimulationGetCurrentTime = _griddyn.gridDynSimulationGetCurrentTime


def gridDynSimulationRun(sim):
    return _griddyn.gridDynSimulationRun(sim)


gridDynSimulationRun = _griddyn.gridDynSimulationRun


def gridDynSimulationRunTo(sim, runToTime):
    return _griddyn.gridDynSimulationRunTo(sim, runToTime)


gridDynSimulationRunTo = _griddyn.gridDynSimulationRunTo


def gridDynSimulationStep(sim):
    return _griddyn.gridDynSimulationStep(sim)


gridDynSimulationStep = _griddyn.gridDynSimulationStep


def gridDynSimulationRunAsync(sim):
    return _griddyn.gridDynSimulationRunAsync(sim)


gridDynSimulationRunAsync = _griddyn.gridDynSimulationRunAsync


def gridDynSimulationRunToAsync(sim, runToTime):
    return _griddyn.gridDynSimulationRunToAsync(sim, runToTime)


gridDynSimulationRunToAsync = _griddyn.gridDynSimulationRunToAsync


def gridDynSimulationStepAsync(sim):
    return _griddyn.gridDynSimulationStepAsync(sim)


gridDynSimulationStepAsync = _griddyn.gridDynSimulationStepAsync


def gridDynSimulationGetStatus(sim):
    return _griddyn.gridDynSimulationGetStatus(sim)


gridDynSimulationGetStatus = _griddyn.gridDynSimulationGetStatus


def getSimulationObject(sim):
    return _griddyn.getSimulationObject(sim)


getSimulationObject = _griddyn.getSimulationObject


def gridDynSimulationGetSolverKey(sim, solverType):
    return _griddyn.gridDynSimulationGetSolverKey(sim, solverType)


gridDynSimulationGetSolverKey = _griddyn.gridDynSimulationGetSolverKey


def gridDynSolverKeyFree(key):
    return _griddyn.gridDynSolverKeyFree(key)


gridDynSolverKeyFree = _griddyn.gridDynSolverKeyFree


def gridDynSimulationStateSize(sim, key):
    return _griddyn.gridDynSimulationStateSize(sim, key)


gridDynSimulationStateSize = _griddyn.gridDynSimulationStateSize


def gridDynSimulationBusCount(sim):
    return _griddyn.gridDynSimulationBusCount(sim)


gridDynSimulationBusCount = _griddyn.gridDynSimulationBusCount


def gridDynSimulationLineCount(sim):
    return _griddyn.gridDynSimulationLineCount(sim)


gridDynSimulationLineCount = _griddyn.gridDynSimulationLineCount


def gridDynSimulationGetResults(*args):
    return _griddyn.gridDynSimulationGetResults(*args)


gridDynSimulationGetResults = _griddyn.gridDynSimulationGetResults


def gridDynSimulationGuessState(sim, time, states, dstate_dt, key):
    return _griddyn.gridDynSimulationGuessState(sim, time, states, dstate_dt, key)


gridDynSimulationGuessState = _griddyn.gridDynSimulationGuessState


def gridDynSimulationSetState(sim, time, states, dstate_dt, key):
    return _griddyn.gridDynSimulationSetState(sim, time, states, dstate_dt, key)


gridDynSimulationSetState = _griddyn.gridDynSimulationSetState


def gridDynSimulationGetStateVariableTypes(sim, types, key):
    return _griddyn.gridDynSimulationGetStateVariableTypes(sim, types, key)


gridDynSimulationGetStateVariableTypes = _griddyn.gridDynSimulationGetStateVariableTypes


def gridDynSimulationResidual(sim, time, resid, states, dstate_dt, key):
    return _griddyn.gridDynSimulationResidual(sim, time, resid, states, dstate_dt, key)


gridDynSimulationResidual = _griddyn.gridDynSimulationResidual


def gridDynSimulationDerivative(sim, time, deriv, states, key):
    return _griddyn.gridDynSimulationDerivative(sim, time, deriv, states, key)


gridDynSimulationDerivative = _griddyn.gridDynSimulationDerivative


def gridDynSimulationAlgebraicUpdate(sim, time, update, states, alpha, key):
    return _griddyn.gridDynSimulationAlgebraicUpdate(sim, time, update, states, alpha, key)


gridDynSimulationAlgebraicUpdate = _griddyn.gridDynSimulationAlgebraicUpdate


def gridDynSimulationJacobian(sim, time, states, dstate_dt, cj, key, insert):
    return _griddyn.gridDynSimulationJacobian(sim, time, states, dstate_dt, cj, key, insert)


gridDynSimulationJacobian = _griddyn.gridDynSimulationJacobian


def gridDynSingleQueryCreate(obj, queryString):
    return _griddyn.gridDynSingleQueryCreate(obj, queryString)


gridDynSingleQueryCreate = _griddyn.gridDynSingleQueryCreate


def gridDynVectorQueryCreate(obj, queryString):
    return _griddyn.gridDynVectorQueryCreate(obj, queryString)


gridDynVectorQueryCreate = _griddyn.gridDynVectorQueryCreate


def gridDynSingleQueryFree(query):
    return _griddyn.gridDynSingleQueryFree(query)


gridDynSingleQueryFree = _griddyn.gridDynSingleQueryFree


def gridDynVectorQueryFree(query):
    return _griddyn.gridDynVectorQueryFree(query)


gridDynVectorQueryFree = _griddyn.gridDynVectorQueryFree


def gridDynSingleQueryRun(query):
    return _griddyn.gridDynSingleQueryRun(query)


gridDynSingleQueryRun = _griddyn.gridDynSingleQueryRun


def gridDynVectorQueryRun(query, data, N):
    return _griddyn.gridDynVectorQueryRun(query, data, N)


gridDynVectorQueryRun = _griddyn.gridDynVectorQueryRun


def gridDynVectorQueryAppend(query, obj, queryString):
    return _griddyn.gridDynVectorQueryAppend(query, obj, queryString)


gridDynVectorQueryAppend = _griddyn.gridDynVectorQueryAppend


def gridDynSingleQueryUpdate(query, obj, queryString):
    return _griddyn.gridDynSingleQueryUpdate(query, obj, queryString)


gridDynSingleQueryUpdate = _griddyn.gridDynSingleQueryUpdate


def gridDynVectorQueryUpdate(query, obj, queryString):
    return _griddyn.gridDynVectorQueryUpdate(query, obj, queryString)


gridDynVectorQueryUpdate = _griddyn.gridDynVectorQueryUpdate


def gridDynEventCreate(eventString, obj):
    return _griddyn.gridDynEventCreate(eventString, obj)


gridDynEventCreate = _griddyn.gridDynEventCreate


def gridDynEventFree(evnt):
    return _griddyn.gridDynEventFree(evnt)


gridDynEventFree = _griddyn.gridDynEventFree


def gridDynEventTrigger(evnt):
    return _griddyn.gridDynEventTrigger(evnt)


gridDynEventTrigger = _griddyn.gridDynEventTrigger


def gridDynEventSchedule(evnt, sim):
    return _griddyn.gridDynEventSchedule(evnt, sim)


gridDynEventSchedule = _griddyn.gridDynEventSchedule


def gridDynEventSetValue(evnt, parameter, value):
    return _griddyn.gridDynEventSetValue(evnt, parameter, value)


gridDynEventSetValue = _griddyn.gridDynEventSetValue


def gridDynEventSetString(evnt, parameter, value):
    return _griddyn.gridDynEventSetString(evnt, parameter, value)


gridDynEventSetString = _griddyn.gridDynEventSetString


def gridDynEventSetFlag(evnt, flag, val):
    return _griddyn.gridDynEventSetFlag(evnt, flag, val)


gridDynEventSetFlag = _griddyn.gridDynEventSetFlag


def gridDynEventSetTarget(evnt, obj):
    return _griddyn.gridDynEventSetTarget(evnt, obj)


gridDynEventSetTarget = _griddyn.gridDynEventSetTarget


def gridDynObjectStateSize(obj, key):
    return _griddyn.gridDynObjectStateSize(obj, key)


gridDynObjectStateSize = _griddyn.gridDynObjectStateSize


def gridDynObjectGuessState(obj, time, states, dstate_dt, key):
    return _griddyn.gridDynObjectGuessState(obj, time, states, dstate_dt, key)


gridDynObjectGuessState = _griddyn.gridDynObjectGuessState


def gridDynObjectSetState(obj, time, states, dstate_dt, key):
    return _griddyn.gridDynObjectSetState(obj, time, states, dstate_dt, key)


gridDynObjectSetState = _griddyn.gridDynObjectSetState


def gridDynObjectGetStateVariableTypes(obj, types, key):
    return _griddyn.gridDynObjectGetStateVariableTypes(obj, types, key)


gridDynObjectGetStateVariableTypes = _griddyn.gridDynObjectGetStateVariableTypes


def gridDynObjectResidual(obj, inputs, inputSize, resid, key):
    return _griddyn.gridDynObjectResidual(obj, inputs, inputSize, resid, key)


gridDynObjectResidual = _griddyn.gridDynObjectResidual


def gridDynObjectDerivative(obj, inputs, inputSize, deriv, key):
    return _griddyn.gridDynObjectDerivative(obj, inputs, inputSize, deriv, key)


gridDynObjectDerivative = _griddyn.gridDynObjectDerivative


def gridDynObjectAlgebraicUpdate(obj, inputs, inputSize, update, alpha, key):
    return _griddyn.gridDynObjectAlgebraicUpdate(obj, inputs, inputSize, update, alpha, key)


gridDynObjectAlgebraicUpdate = _griddyn.gridDynObjectAlgebraicUpdate


def gridDynObjectJacobian(obj, inputs, inputSize, cj, insert, key):
    return _griddyn.gridDynObjectJacobian(obj, inputs, inputSize, cj, insert, key)


gridDynObjectJacobian = _griddyn.gridDynObjectJacobian


def gridDynObjectIoPartialDerivatives(obj, inputs, inputSize, insert, key):
    return _griddyn.gridDynObjectIoPartialDerivatives(obj, inputs, inputSize, insert, key)


gridDynObjectIoPartialDerivatives = _griddyn.gridDynObjectIoPartialDerivatives


def gridDynObjectOutputPartialDerivatives(obj, inputs, inputSize, insert, key):
    return _griddyn.gridDynObjectOutputPartialDerivatives(obj, inputs, inputSize, insert, key)


gridDynObjectOutputPartialDerivatives = _griddyn.gridDynObjectOutputPartialDerivatives
# This file is compatible with both classic and new-style classes.
